//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_BUSINESS_TYPE
    {
        public string GUID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string TYPE { get; set; }
        public string IS_DEFAULT { get; set; }
        public string CUSTOMS_TYPES { get; set; }
        public string IS_BOCI { get; set; }
        public string HG_TYPES { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string FK_BUSINESS_TYPE { get; set; }
        public string IS_OLD_INV { get; set; }
        public string BOCI_TYPE { get; set; }
        public string RECEIVE_LIMIT_TYPE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
