//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_COMPLEX_CALC
    {
        public string GUID { get; set; }
        public string CONDITION { get; set; }
        public string RESULT { get; set; }
        public string MEMO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string PARENT_GUID { get; set; }
        public Nullable<decimal> SEQ { get; set; }
    }
}
