//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_EXCHANGE
    {
        public string GUID { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> YEAR { get; set; }
        public Nullable<decimal> MONTH { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
