//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_STATUS
    {
        public string GUID { get; set; }
        public string CODE { get; set; }
        public string NAME_1 { get; set; }
        public string NAME_2 { get; set; }
        public string NAME_3 { get; set; }
        public string NAME_4 { get; set; }
        public string NAME_5 { get; set; }
        public string NAME_6 { get; set; }
        public string NAME_7 { get; set; }
        public string NAME_8 { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string TYPE { get; set; }
        public string WMS_CODE { get; set; }
    }
}
