//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMS_AUTO_DATA
    {
        public string GUID { get; set; }
        public string OP_NO { get; set; }
        public string CHARGE_CODE { get; set; }
        public decimal AMOUNT { get; set; }
        public string MONEY_CODE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string AR_AP { get; set; }
        public string NET { get; set; }
        public string EXE_ID { get; set; }
        public string TRACE_ID { get; set; }
        public string QUOTE_DETAIL_GUID { get; set; }
        public string QUOTE_MEMO { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
