//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMS_AP
    {
        public string GUID { get; set; }
        public string OP_NO { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string CHARGE_CODE { get; set; }
        public decimal AMOUNT { get; set; }
        public string MONEY_CODE { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string SEND_USER { get; set; }
        public Nullable<System.DateTime> AUDIT_DATE { get; set; }
        public string AUDIT_USER { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> KP_DATE { get; set; }
        public Nullable<decimal> XZ_AMOUNT { get; set; }
        public Nullable<System.DateTime> XZ_DATE { get; set; }
        public string STATUS { get; set; }
        public string DEPT_ID { get; set; }
        public Nullable<decimal> SYS_AMOUNT { get; set; }
        public Nullable<System.DateTime> OP_DATE { get; set; }
        public string OP_TYPE { get; set; }
        public Nullable<decimal> LOCAL_AMOUNT { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string DZD_NO { get; set; }
        public Nullable<System.DateTime> DZ_DATE { get; set; }
        public string DZ_USER { get; set; }
        public string KP_USER { get; set; }
        public string XZ_USER { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
