//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOCI_RULE
    {
        public string GUID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string DELIVERY_COMPANY { get; set; }
        public string URGENT { get; set; }
        public string IS_SINGLE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string PICK_METHOD { get; set; }
        public Nullable<decimal> NUM { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public Nullable<decimal> ORDER_NUM { get; set; }
        public Nullable<decimal> ORDER_LINE_NUM { get; set; }
        public Nullable<System.DateTime> BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> TIME { get; set; }
        public string STATUS { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
