//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSK_LOG
    {
        public string GUID { get; set; }
        public string BSK_NO { get; set; }
        public Nullable<System.DateTime> BSK_DQ_DATE { get; set; }
        public Nullable<decimal> BSK_YQ_NUM { get; set; }
        public string STATUS { get; set; }
        public string BSK_WAY { get; set; }
        public string OP_USER { get; set; }
        public string OP_USER_NAME { get; set; }
        public Nullable<System.DateTime> OP_DATE { get; set; }
        public string MEMO { get; set; }
        public string STATUS_TYPE { get; set; }
        public string I_E_FLAG { get; set; }
        public string RECEIVE_ORDER_NO { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
