//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_TRANSFER_DETAIL
    {
        public string GUID { get; set; }
        public string INVENTORY_GUID { get; set; }
        public string TRANSFER_NO { get; set; }
        public string WH_CODE { get; set; }
        public Nullable<decimal> PICK_QTY { get; set; }
        public string PLT_NO { get; set; }
        public string ZONE_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string LOC_CODE { get; set; }
        public string DAMAGE_FLAG { get; set; }
        public string FROM_CUSTOMER_CODE { get; set; }
        public string FROM_SKU { get; set; }
        public string FROM_CONSIGNEE_CODE { get; set; }
        public string FROM_CONSIGNEE_SKU { get; set; }
        public string FROM_NOTIFY_CODE { get; set; }
        public string FROM_NOTIFY_SKU { get; set; }
        public string FROM_LOT_NO { get; set; }
        public string FROM_INV_NO { get; set; }
        public string FROM_PO_NO { get; set; }
        public string FROM_COUNTRY { get; set; }
        public Nullable<System.DateTime> FROM_DATECODE { get; set; }
        public string FROM_CUSTOMER_REF_NO { get; set; }
        public string FROM_CONSIGNEE_REF_NO { get; set; }
        public string FROM_NOTIFY_REF_NO { get; set; }
        public Nullable<decimal> FROM_PIRCE { get; set; }
        public string FROM_UDF1 { get; set; }
        public string FROM_UDF2 { get; set; }
        public string FROM_UDF3 { get; set; }
        public string FROM_UDF4 { get; set; }
        public string FROM_UDF5 { get; set; }
        public string FROM_UDF6 { get; set; }
        public string FROM_UDF7 { get; set; }
        public string FROM_UDF8 { get; set; }
        public string FROM_UDF9 { get; set; }
        public string FROM_UDF10 { get; set; }
        public string TO_CUSTOMER_CODE { get; set; }
        public string TO_SKU { get; set; }
        public string TO_CONSIGNEE_CODE { get; set; }
        public string TO_CONSIGNEE_SKU { get; set; }
        public string TO_NOTIFY_CODE { get; set; }
        public string TO_NOTIFY_SKU { get; set; }
        public string TO_LOT_NO { get; set; }
        public string TO_INV_NO { get; set; }
        public string TO_PO_NO { get; set; }
        public string TO_COUNTRY { get; set; }
        public Nullable<System.DateTime> TO_DATECODE { get; set; }
        public string TO_CUSTOMER_REF_NO { get; set; }
        public string TO_CONSIGNEE_REF_NO { get; set; }
        public string TO_NOTIFY_REF_NO { get; set; }
        public Nullable<decimal> TO_PIRCE { get; set; }
        public string TO_UDF1 { get; set; }
        public string TO_UDF2 { get; set; }
        public string TO_UDF3 { get; set; }
        public string TO_UDF4 { get; set; }
        public string TO_UDF5 { get; set; }
        public string TO_UDF6 { get; set; }
        public string TO_UDF7 { get; set; }
        public string TO_UDF8 { get; set; }
        public string TO_UDF9 { get; set; }
        public string TO_UDF10 { get; set; }
        public Nullable<decimal> PACK1 { get; set; }
        public Nullable<decimal> PACK2 { get; set; }
        public Nullable<decimal> PACK3 { get; set; }
        public Nullable<decimal> PACK4 { get; set; }
        public Nullable<decimal> PACK5 { get; set; }
        public Nullable<decimal> PACK6 { get; set; }
        public Nullable<decimal> UNIT_GW { get; set; }
        public Nullable<decimal> UNIT_NW { get; set; }
        public Nullable<decimal> UNIT_VOLUME { get; set; }
        public string REWORK_FLAG { get; set; }
        public string WORK_STATUS { get; set; }
        public string QC_STATUS { get; set; }
        public string LOCKING_FLAG { get; set; }
        public string PACK1_UNIT { get; set; }
        public string PACK2_UNIT { get; set; }
        public string PACK3_UNIT { get; set; }
        public string PACK4_UNIT { get; set; }
        public string PACK5_UNIT { get; set; }
        public string PACK6_UNIT { get; set; }
        public string TS_VERSION { get; set; }
        public string NEW_INVENTORY_GUID { get; set; }
        public string EXE_TYPE { get; set; }
        public Nullable<decimal> RECEIVE_QTY { get; set; }
        public Nullable<decimal> TRANS_IN_LINE_NO { get; set; }
        public string TRANS_IN_TYPE { get; set; }
        public string UNIQUE_CODE { get; set; }
        public Nullable<System.DateTime> CUSTOMER_SHIP_DATE { get; set; }
        public string SPEC { get; set; }
        public string MATERIAL { get; set; }
        public string PACKAGE_NO { get; set; }
        public string OWN_NO { get; set; }
        public string FROM_GOODS_PACK_NO { get; set; }
        public string IS_CONTROL { get; set; }
        public string TO_GOODS_PACK_NO { get; set; }
        public string FROM_PACK_NO { get; set; }
        public string TO_PACK_NO { get; set; }
        public Nullable<System.DateTime> FROM_PUTAWAY_DATE { get; set; }
        public string FROM_SHIPPER_CODE { get; set; }
        public string FROM_PACK_STR { get; set; }
        public Nullable<decimal> FROM_YB_LINE_NO { get; set; }
        public string FROM_UNIQUE_CODE { get; set; }
        public Nullable<System.DateTime> FROM_CUSTOMER_SHIP_DATE { get; set; }
        public string FROM_SPEC { get; set; }
        public string FROM_MATERIAL { get; set; }
        public string FROM_PACKAGE_NO { get; set; }
        public string FROM_OWN_NO { get; set; }
        public string FROM_IS_CONTROL { get; set; }
        public string FROM_RECEIVE_NO { get; set; }
        public Nullable<System.DateTime> TO_PUTAWAY_DATE { get; set; }
        public string TO_SHIPPER_CODE { get; set; }
        public string TO_PACK_STR { get; set; }
        public Nullable<decimal> TO_YB_LINE_NO { get; set; }
        public string TO_UNIQUE_CODE { get; set; }
        public Nullable<System.DateTime> TO_CUSTOMER_SHIP_DATE { get; set; }
        public string TO_SPEC { get; set; }
        public string TO_MATERIAL { get; set; }
        public string TO_PACKAGE_NO { get; set; }
        public string TO_OWN_NO { get; set; }
        public string TO_IS_CONTROL { get; set; }
        public string TO_RECEIVE_NO { get; set; }
        public string TO_UDF11 { get; set; }
        public string TO_UDF12 { get; set; }
        public string TO_UDF13 { get; set; }
        public string TO_UDF14 { get; set; }
        public string TO_UDF15 { get; set; }
        public string FROM_UDF11 { get; set; }
        public string FROM_UDF12 { get; set; }
        public string FROM_UDF13 { get; set; }
        public string FROM_UDF14 { get; set; }
        public string FROM_UDF15 { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
