//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_TRANSFER
    {
        public string GUID { get; set; }
        public string TRANSFER_NO { get; set; }
        public string WH_CODE { get; set; }
        public string STATUS { get; set; }
        public string REFERENCE_NO { get; set; }
        public string CUSTOMER_REF_NO { get; set; }
        public string BILLING_OBJ { get; set; }
        public string TRANSFER_TYPE { get; set; }
        public Nullable<System.DateTime> TRANSFER_DATE { get; set; }
        public string CONFIRM_USER { get; set; }
        public Nullable<System.DateTime> CONFIRM_DATE { get; set; }
        public string REMARK { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string TS_VERSION { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
