//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODESMITH_EXTENDED_PROPERTIES
    {
        public string CONTAINER_OBJECT_OWNER { get; set; }
        public string OBJECT_NAME { get; set; }
        public string CODESMITH_SCHEMA_TYPE { get; set; }
        public string PROPERTY_NAME { get; set; }
        public string PROPERTY_VALUE { get; set; }
        public string CLR_TYPE { get; set; }
    }
}
