//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_EXPRESS
    {
        public string GUID { get; set; }
        public string EXPRESS_CODE { get; set; }
        public string MD_PRINT_TYPE { get; set; }
        public string MD_PRINT_URL { get; set; }
        public string MD_PRINT_USER { get; set; }
        public string MD_PRINT_PWD { get; set; }
        public string EXPRESS_API { get; set; }
        public string BL_CALL_TYPE { get; set; }
        public string BL_CALL_FUNCTION { get; set; }
        public string INFOR_CALL_TYPE { get; set; }
        public string INFOR_CALL_FUNCTION { get; set; }
        public string STATUS { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CONN_XQL { get; set; }
        public string PRE_TIP { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
