//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_ENTERPRISE
    {
        public string GUID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public string EN_NAME { get; set; }
        public string OTHER_NAME { get; set; }
        public string CUSTOM_NO { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS_EN { get; set; }
        public string PERSON { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
        public string COMPANY_TYPE { get; set; }
        public string COMPANY_TYPE_NAME { get; set; }
        public string CUSTOMER_B2B { get; set; }
        public string TAX { get; set; }
        public string LOGO { get; set; }
        public string APPNAME { get; set; }
        public Nullable<System.DateTime> END_USER_DATE { get; set; }
        public string STATUS { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
