//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_RELATION
    {
        public string GUID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_ALIAS1 { get; set; }
        public string CUSTOMER_ALIAS2 { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string CONSIGNEE_ALIAS1 { get; set; }
        public string CONSIGNEE_ALIAS2 { get; set; }
        public string NOTIFY_CODE { get; set; }
        public string NOTIFY_ALIAS1 { get; set; }
        public string NOTIFY_ALIAS2 { get; set; }
        public string REFERENCE_NUM1 { get; set; }
        public string REFERENCE_NUM2 { get; set; }
        public string REFERENCE_NUM3 { get; set; }
        public string NOTES { get; set; }
        public string MEMO { get; set; }
        public string STATUS { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CUSTOMER_GUID { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
