//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_TEMPLATE
    {
        public string GUID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string BG_MODE { get; set; }
        public string OP_BG_MODEL { get; set; }
        public string WH_CODE { get; set; }
        public string SHIPPER_CONSIGNEE { get; set; }
        public string BILLING_OBJ { get; set; }
        public string IS_ZX { get; set; }
        public string IS_BJ { get; set; }
        public string IS_FJ { get; set; }
        public string DAMAGE_FLAG { get; set; }
        public Nullable<decimal> PIECES { get; set; }
        public string PIECES_UNIT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string IS_BS { get; set; }
        public string MEMO { get; set; }
        public string BALANCE_MEMO { get; set; }
        public string CUSTOMER_GUID { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
