//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string GUID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public string EN_NAME { get; set; }
        public string OTHER_NAME { get; set; }
        public string CUSTOM_NO { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS_EN { get; set; }
        public string PERSON { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
        public string CONTRACT { get; set; }
        public Nullable<System.DateTime> CONTRACT_FROM_DATE { get; set; }
        public Nullable<System.DateTime> CONTRACT_TO_DATE { get; set; }
        public string ACCOUNT { get; set; }
        public string BANK { get; set; }
        public string TAX { get; set; }
        public string CREDIT_RATING { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public Nullable<decimal> CHARGE_CYCLE { get; set; }
        public string TREATY { get; set; }
        public string RECEIVE_NOTES { get; set; }
        public string RELEASE_NOTES { get; set; }
        public string WORK_NOTES { get; set; }
        public string NOTES { get; set; }
        public string STATUS { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string ASSIGN_METHOD { get; set; }
        public string PACK_METHOD { get; set; }
        public string PUTAWAY_TYPE { get; set; }
        public string BAR_CODE { get; set; }
        public string COMPANY_TYPE { get; set; }
        public string COMPANY_TYPE_NAME { get; set; }
        public string FLAG { get; set; }
        public string CUSTOMER_B2B { get; set; }
        public string IS_CUSTOM { get; set; }
        public string IS_LOCK { get; set; }
        public string EMS_NO { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
        public string IS_NB { get; set; }
    }
}
