//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECI_TABLE_TABITEM
    {
        public string GUID { get; set; }
        public string TABLE_GUID { get; set; }
        public string TAB_NAME { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string STATUS { get; set; }
        public string MEMO { get; set; }
        public string CONTROL_ID { get; set; }
        public string CONTROL_PATH { get; set; }
        public string SHOW_MODE { get; set; }
    }
}
