//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECI_TABLE_GROUP
    {
        public string GUID { get; set; }
        public string DISPLAY_TYPE { get; set; }
        public Nullable<decimal> COLUMN_COUNT { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string MEMO { get; set; }
        public string GROUP_CODE { get; set; }
        public string GROUP_NAME { get; set; }
        public string TABLE_GUID { get; set; }
    }
}
