//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECI_TABLE
    {
        public string TABLE_NAME { get; set; }
        public string MAIN_ALIAS { get; set; }
        public string GUID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string TABLE_WIDTH { get; set; }
        public string CONDITION { get; set; }
        public Nullable<decimal> COLUMN_COUNT { get; set; }
        public string ADVANCE_CONFIG { get; set; }
        public string CODE { get; set; }
        public string DEFAULT_CONDITION { get; set; }
        public Nullable<decimal> LOAD_DATA { get; set; }
        public Nullable<decimal> FUNCTION_ADD { get; set; }
        public Nullable<decimal> FUNCTION_DELETE { get; set; }
        public Nullable<decimal> FUNCTION_EXCEL { get; set; }
        public Nullable<decimal> FUNCTION_EDIT { get; set; }
        public string DEFAULT_SORT { get; set; }
        public string JS_FILE { get; set; }
        public string GRID_SQL { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> DEFAULT_PAGE_SIZE { get; set; }
        public string STYLE_FILE { get; set; }
        public Nullable<decimal> FUNCTION_BACK { get; set; }
        public string REMARKS { get; set; }
        public Nullable<decimal> QUERY_COLUMN_COUNT { get; set; }
        public string PARAM { get; set; }
        public string JS_SCRIPT { get; set; }
        public string DEFAULT_SELECT { get; set; }
        public string GRID_LAYOUT { get; set; }
        public string KEEP_ADD_STATUS { get; set; }
        public string ADD_SEQ { get; set; }
        public string FILE_UPLOAD { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string PL_VERSION { get; set; }
        public string PL_SAVE_FIXED { get; set; }
        public Nullable<decimal> EDIT_FUNCTION_SAVE { get; set; }
        public Nullable<decimal> EDIT_FUNCTION_COPY { get; set; }
        public Nullable<decimal> EDIT_FUNCTION_CLOSE { get; set; }
        public string HAS_DATA_SOURCE { get; set; }
        public string PRIMARY_KEY_INPUT { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public string DATA_SOURCE { get; set; }
        public string SHARE_CONFIG { get; set; }
        public Nullable<decimal> EDIT_FUNCTION_ADD { get; set; }
        public Nullable<decimal> FUNCTION_SAVE_BACK { get; set; }
        public string ADVANCE_CONFIG_SERVER { get; set; }
    }
}
