//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECI_SYS_LOG
    {
        public string GUID { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string TYPE { get; set; }
        public string URL { get; set; }
        public string EVENT_TARGET { get; set; }
        public string EVENT_ARGUMENT { get; set; }
        public string KEY_NO { get; set; }
        public string PARAM { get; set; }
        public Nullable<decimal> SUCCESS { get; set; }
        public string MESSAGE { get; set; }
        public string IP { get; set; }
        public string BROWSER { get; set; }
        public string OS { get; set; }
        public string PAGE_TITLE { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string SERVICE_ID { get; set; }
        public Nullable<decimal> EXECUTE_BEGIN { get; set; }
        public Nullable<decimal> EXECUTE_END { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string SESSION_ID { get; set; }
        public string AJAX_ACTION { get; set; }
        public string ERROR_TYPE { get; set; }
        public string LOGIN_NO { get; set; }
        public string USER_COMPANY { get; set; }
    }
}
