//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECI_TABLE_FUNCTION
    {
        public string GUID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string FUNCTION_NAME { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string EXTEND_TYPE { get; set; }
        public string GRID_LINK_URL { get; set; }
        public string JS_SCRIPT { get; set; }
        public string SHOW_MODE { get; set; }
        public string CONTROL_ID { get; set; }
        public string HOT_KEY { get; set; }
        public string WIDTH { get; set; }
        public string CSS { get; set; }
        public string AUTHORITY_ID { get; set; }
        public string SHOW_POSITION { get; set; }
        public string STATUS { get; set; }
        public string TABLE_GUID { get; set; }
        public string MEMO { get; set; }
        public string ICON { get; set; }
        public string FUNCTION_DATA { get; set; }
        public string WCF_SERVICE_DATA { get; set; }
        public string CONTROLLER_ACTION { get; set; }
        public string PROC_NAME { get; set; }
    }
}
