//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECI_DATA_HELP
    {
        public string GUID { get; set; }
        public string QUERY_TYPE { get; set; }
        public string STATUS { get; set; }
        public string SQL { get; set; }
        public string MEMO { get; set; }
        public string DATA_CHANGE_CODE { get; set; }
        public string DATA_CHANGE_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string ECI_LOCK { get; set; }
        public string CONVERT_SQL { get; set; }
        public string SYS { get; set; }
        public string PL_VERSION { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string NEED_DOWNLOAD { get; set; }
        public string SORT_FIELD { get; set; }
        public string MEMO_DETAIL { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public string ADMIN_LOCK { get; set; }
        public string CODE_MEMO { get; set; }
        public string NAME_MEMO { get; set; }
        public string CHOOSE_SHOW { get; set; }
        public string ASSEMBLY_NAME { get; set; }
        public string USE_CACHE { get; set; }
        public string FILTER { get; set; }
        public string COMPARE_TYPE { get; set; }
        public string QUERY_FIELD { get; set; }
        public string LAYOUT { get; set; }
    }
}
