//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECI_TABLE_ELEMENT
    {
        public string CODE { get; set; }
        public string MAIN_ALIAS { get; set; }
        public string PHYSICAL_TYPE { get; set; }
        public Nullable<decimal> FIELD_LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public string LINK_URL { get; set; }
        public string SQL_ATTRIBUTE { get; set; }
        public string TABLE_GUID { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string DICTIONARY_TYPE { get; set; }
        public Nullable<decimal> GRID_SHOW { get; set; }
        public Nullable<decimal> EDIT_SHOW { get; set; }
        public Nullable<decimal> QUERY_SHOW { get; set; }
        public string GUID { get; set; }
        public Nullable<decimal> PRIMARY_KEY { get; set; }
        public Nullable<decimal> NULLABLE_KEY { get; set; }
        public Nullable<decimal> UNIQUE_KEY { get; set; }
        public string DICTIONARY_TYPE_CONFIG { get; set; }
        public Nullable<decimal> QUERY_SEQ { get; set; }
        public Nullable<decimal> EDIT_SEQ { get; set; }
        public string EDIT_LOCK_MODE { get; set; }
        public string SYSTEM_DATA { get; set; }
        public string SYSTEM_DATA_TRIGGER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<decimal> COLSPAN { get; set; }
        public string SHOW_CONVERT { get; set; }
        public string PRIMARY_CREATOR { get; set; }
        public Nullable<decimal> COPY_REMOVE_DATA { get; set; }
        public Nullable<decimal> QUERY_ADD_EMPTY { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<decimal> EDIT_HIDE_LABEL { get; set; }
        public Nullable<decimal> GRID_SEQ { get; set; }
        public string CSS { get; set; }
        public string WRAP { get; set; }
        public string CONTROL_WIDTH { get; set; }
        public string NOT_SAVE { get; set; }
        public string DEFAULT_VALUE_QUERY { get; set; }
        public string HIDDEN { get; set; }
        public string DB_FIELD { get; set; }
        public string DATA_FORMAT_GRID { get; set; }
        public string DATA_SOURCE { get; set; }
        public string GRID_HEAD_ALIGN { get; set; }
        public string GRID_ITEM_ALIGN { get; set; }
        public string SHOW_TIP { get; set; }
        public string SQL_ATTRIBUTE_EX { get; set; }
        public string CONTRACT_TEXT { get; set; }
        public string TO_DBC { get; set; }
        public string EDIT_TIP { get; set; }
        public string DATA_FORMAT_EDIT { get; set; }
        public string EXPORT_TYPE { get; set; }
        public string AFTER_ELEMENT { get; set; }
        public string EDIT_LABEL_TIP { get; set; }
        public string EDIT_NOT_SAVE { get; set; }
        public string MEMO { get; set; }
        public string AUTO_UPPER { get; set; }
        public Nullable<decimal> BATCH_EDIT { get; set; }
    }
}
