//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMS_HEAD
    {
        public string EMS_NO { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public string BUSINESS_CODE { get; set; }
        public string BUSINESS_NAME { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string CONSIGNEE_NAME { get; set; }
        public string LISENCE_NO { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
