//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_DEC_HEAD
    {
        public string GUID { get; set; }
        public string MESSAGE_ID { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public string VERSION { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string REMARK { get; set; }
        public string OP_NO { get; set; }
        public string CUSTOMER_JOB_NO { get; set; }
        public string CUSTOMER_SYS { get; set; }
        public string OP_FLAG { get; set; }
        public string I_E_FLAG { get; set; }
        public string INV_NO { get; set; }
        public string DEC_NO { get; set; }
        public string QY_DEC_NO { get; set; }
        public string CONTRACT_NO { get; set; }
        public string SHIPPER_CODE { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public Nullable<decimal> TOTOAL_PIECE { get; set; }
        public string PIECE_UNIT { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_NW { get; set; }
        public Nullable<decimal> TOTAL_GW { get; set; }
        public Nullable<decimal> TOTAL_VOLUME { get; set; }
        public Nullable<System.DateTime> DEC_DATE { get; set; }
        public string BGH { get; set; }
        public string YLR_NO { get; set; }
        public Nullable<System.DateTime> FX_DATE { get; set; }
        public string DEC_CUSTOM { get; set; }
        public string JOB_NO { get; set; }
        public Nullable<decimal> CC_DEC_PIAO { get; set; }
        public Nullable<decimal> CC_DEC_ZHANG { get; set; }
        public Nullable<decimal> QY_DEC_PIAO { get; set; }
        public Nullable<decimal> QY_DEC_ZHANG { get; set; }
        public Nullable<decimal> RETURN_QTY { get; set; }
        public Nullable<decimal> DELETE_QTY { get; set; }
        public Nullable<decimal> CHANGE_QTY { get; set; }
        public string DEC_MEMO { get; set; }
        public Nullable<System.DateTime> EXE_DATE { get; set; }
        public string EXE_STATUS { get; set; }
        public string EXE_EXCEPTION { get; set; }
        public string EXE_FLAG { get; set; }
    }
}
