//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ORDERS
    {
        public string GUID { get; set; }
        public string MESSAGE_ID { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public string VERSION { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string REMARK { get; set; }
        public string ORDER_TYPE { get; set; }
        public string ORDER_NO { get; set; }
        public string CUSTOMER_ROLE { get; set; }
        public string CUSTOMER_B2B { get; set; }
        public string CUSTOMER_JOB_NO { get; set; }
        public string CUSTOMER_SYS { get; set; }
        public string OP_FLAG { get; set; }
        public string FILE_URL { get; set; }
        public string WH_CODE { get; set; }
        public string OWNER { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string BG_MODE { get; set; }
        public string OP_BG_MODEL { get; set; }
        public string SHIPPER_CONSIGNEE { get; set; }
        public string BILLING_OBJ { get; set; }
        public Nullable<System.DateTime> PRE_DATE { get; set; }
        public Nullable<decimal> EXPECTED_PIECES { get; set; }
        public string PIECES_UNIT { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> EXPECTED_AMOUNT { get; set; }
        public Nullable<decimal> EXPECTED_GW { get; set; }
        public Nullable<decimal> EXPECTED_NW { get; set; }
        public Nullable<decimal> EXPECTED_VOLUME { get; set; }
        public string DAMAGE_FLAG { get; set; }
        public string ORDER_INVOICE { get; set; }
        public string BL_NO { get; set; }
        public string EXTERNAL_NO1 { get; set; }
        public string EXTERNAL_NO2 { get; set; }
        public string PICK_EXPLAIN { get; set; }
        public string EXPRESS { get; set; }
        public string EXPRESS_NO { get; set; }
        public string DELIVERY_PAY_TYPE { get; set; }
        public string DELIVERY_PERSON { get; set; }
        public string DELIVERY_COMPANY { get; set; }
        public string DELIVERY_TEL { get; set; }
        public string DELIVERY_POSTCODE { get; set; }
        public string DELIVERY_ADDR1 { get; set; }
        public string DELIVERY_ADDR2 { get; set; }
        public string DELIVERY_ADDR3 { get; set; }
        public string DELIVERY_ADDR4 { get; set; }
        public string DELIVERY_PLAN { get; set; }
        public Nullable<decimal> DELIVERY_FEE { get; set; }
        public Nullable<System.DateTime> EXE_DATE { get; set; }
        public string EXE_STATUS { get; set; }
        public string EXE_EXCEPTION { get; set; }
        public string EXE_FLAG { get; set; }
        public string EMS_NO { get; set; }
        public string EXTERNAL_KEY { get; set; }
        public string IS_LOCK { get; set; }
        public string IS_BS { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string HFD_NO { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string DECLARE_NO { get; set; }
        public string CONTRACT_NO { get; set; }
        public string OP_DECLARE_NO { get; set; }
    }
}
