//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_PRODUCT
    {
        public string GUID { get; set; }
        public string HEAD_GUID { get; set; }
        public string OP_FLAG { get; set; }
        public string CUSTOMER_B2B { get; set; }
        public string SKU { get; set; }
        public string SKU_DESC { get; set; }
        public string BAR_CODE { get; set; }
        public string STORAGE_TYPE { get; set; }
        public Nullable<decimal> SAFETY_STOCK { get; set; }
        public string OTHER_NAME { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string MEMO { get; set; }
        public string UDF1 { get; set; }
        public string UNIT { get; set; }
    }
}
