//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_OP
    {
        public string OP_NO { get; set; }
        public string RECEIVE_NO { get; set; }
        public string RECEIVE_BATCH_NO { get; set; }
        public string PUTAWAY_NO { get; set; }
        public string PLT_NO { get; set; }
        public string WH_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string SKU { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string CONSIGNEE_SKU { get; set; }
        public string NOTIFY_CODE { get; set; }
        public string NOTIFY_SKU { get; set; }
        public string LOT_NO { get; set; }
        public string INV_NO { get; set; }
        public string PO_NO { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> DATECODE { get; set; }
        public string CUSTOMER_REF_NO { get; set; }
        public string CONSIGNEE_REF_NO { get; set; }
        public string NOTIFY_REF_NO { get; set; }
        public Nullable<decimal> PIRCE { get; set; }
        public Nullable<decimal> GW { get; set; }
        public Nullable<decimal> NW { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public decimal QTY { get; set; }
        public string REWORK_FLAG { get; set; }
        public string WORK_STATUS { get; set; }
        public string QC_STATUS { get; set; }
        public string ZONE_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string LOC_CODE { get; set; }
        public Nullable<decimal> DAMAGE_FLAG { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public Nullable<decimal> PACK1 { get; set; }
        public Nullable<decimal> PACK2 { get; set; }
        public Nullable<decimal> PACK3 { get; set; }
        public Nullable<decimal> PACK4 { get; set; }
        public Nullable<decimal> PACK5 { get; set; }
        public Nullable<decimal> PACK6 { get; set; }
        public string PACK1_UNIT { get; set; }
        public string PACK2_UNIT { get; set; }
        public string PACK3_UNIT { get; set; }
        public string PACK4_UNIT { get; set; }
        public string PACK5_UNIT { get; set; }
        public string PACK6_UNIT { get; set; }
        public Nullable<System.DateTime> PUTAWAY_DATE { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public string PRICE_CODE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string DETAIL_TABLE { get; set; }
        public string CREATE_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime OP_DATE { get; set; }
        public string TEMP { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
