//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION_TRANSFER_DETAIL
    {
        public string GUID { get; set; }
        public string INVENTORY_GUID { get; set; }
        public string TRANSFER_NO { get; set; }
        public string WH_CODE { get; set; }
        public Nullable<decimal> PICK_QTY { get; set; }
        public string FROM_PLT_NO { get; set; }
        public string FROM_ZONE_CODE { get; set; }
        public string FROM_AREA_CODE { get; set; }
        public string FROM_LOC_CODE { get; set; }
        public string FROM_DAMAGE_FLAG { get; set; }
        public string TO_PLT_NO { get; set; }
        public string TO_ZONE_CODE { get; set; }
        public string TO_AREA_CODE { get; set; }
        public string TO_LOC_CODE { get; set; }
        public string TO_DAMAGE_FLAG { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string SKU { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string CONSIGNEE_SKU { get; set; }
        public string NOTIFY_CODE { get; set; }
        public string NOTIFY_SKU { get; set; }
        public string LOT_NO { get; set; }
        public string INV_NO { get; set; }
        public string PO_NO { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> DATECODE { get; set; }
        public string CUSTOMER_REF_NO { get; set; }
        public string CONSIGNEE_REF_NO { get; set; }
        public string NOTIFY_REF_NO { get; set; }
        public Nullable<decimal> PIRCE { get; set; }
        public Nullable<decimal> UNIT_GW { get; set; }
        public Nullable<decimal> UNIT_NW { get; set; }
        public Nullable<decimal> UNIT_VOLUME { get; set; }
        public string REWORK_FLAG { get; set; }
        public string WORK_STATUS { get; set; }
        public string QC_STATUS { get; set; }
        public string LOCKING_FLAG { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public Nullable<decimal> PACK1 { get; set; }
        public Nullable<decimal> PACK2 { get; set; }
        public Nullable<decimal> PACK3 { get; set; }
        public Nullable<decimal> PACK4 { get; set; }
        public Nullable<decimal> PACK5 { get; set; }
        public Nullable<decimal> PACK6 { get; set; }
        public string PACK1_UNIT { get; set; }
        public string PACK2_UNIT { get; set; }
        public string PACK3_UNIT { get; set; }
        public string PACK4_UNIT { get; set; }
        public string PACK5_UNIT { get; set; }
        public string PACK6_UNIT { get; set; }
        public string TS_VERSION { get; set; }
        public string NEW_INVENTORY_GUID { get; set; }
        public string TEMP { get; set; }
        public Nullable<decimal> RECEIVE_QTY { get; set; }
        public Nullable<decimal> TRANS_IN_LINE_NO { get; set; }
        public string TRANS_IN_TYPE { get; set; }
        public string UNIQUE_CODE { get; set; }
        public Nullable<System.DateTime> CUSTOMER_SHIP_DATE { get; set; }
        public string SPEC { get; set; }
        public string MATERIAL { get; set; }
        public string PACKAGE_NO { get; set; }
        public string OWN_NO { get; set; }
        public string GOODS_PACK_NO { get; set; }
        public string IS_CONTROL { get; set; }
        public string TO_GOODS_PACK_NO { get; set; }
        public string IS_NEWLPN { get; set; }
        public string IS_NEWCTN { get; set; }
        public string PACK_STR { get; set; }
        public string PACK_STR_TO { get; set; }
        public Nullable<decimal> PACK1_TO { get; set; }
        public Nullable<decimal> PACK2_TO { get; set; }
        public Nullable<decimal> PACK3_TO { get; set; }
        public Nullable<decimal> PACK4_TO { get; set; }
        public Nullable<decimal> PACK5_TO { get; set; }
        public Nullable<decimal> PACK6_TO { get; set; }
        public string PACK1_UNIT_TO { get; set; }
        public string PACK2_UNIT_TO { get; set; }
        public string PACK3_UNIT_TO { get; set; }
        public string PACK4_UNIT_TO { get; set; }
        public string PACK5_UNIT_TO { get; set; }
        public string PACK6_UNIT_TO { get; set; }
        public string UDF11 { get; set; }
        public string UDF12 { get; set; }
        public string UDF13 { get; set; }
        public string UDF14 { get; set; }
        public string UDF15 { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
