//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_CUST_QUOTE_DETAIL
    {
        public string GUID { get; set; }
        public string PRICE_CODE { get; set; }
        public Nullable<System.DateTime> BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string CHARGE_CODE { get; set; }
        public string CALC_TYPE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> MIN_VALUE { get; set; }
        public Nullable<decimal> MAX_VALUE { get; set; }
        public string CONDITION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string CALC_AMOUNT { get; set; }
        public string CALC_EXPRESSION { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string MEMO { get; set; }
        public string CALC_GRADE { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
