//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_CUST_TEMPLATE_DTL
    {
        public string GUID { get; set; }
        public string PRICE_CODE { get; set; }
        public string CHARGE_CODE { get; set; }
        public string MONEY_CODE { get; set; }
        public string SERVICE_NO { get; set; }
        public string NET { get; set; }
        public string CALC_TYPE { get; set; }
        public string CALC_AMOUNT { get; set; }
        public string CALC_GRADE { get; set; }
        public Nullable<decimal> QUOTE_PRICE { get; set; }
        public Nullable<decimal> COST_MIN { get; set; }
        public Nullable<decimal> COST_MAX { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string STATUS { get; set; }
        public string CONN_GUID { get; set; }
        public string CALC_FORMULA { get; set; }
        public string CONDITION { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
