//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class OracleEntities : DbContext
    {
        public OracleEntities()
            : base("name=OracleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BD_AREA> BD_AREA { get; set; }
        public DbSet<BD_BACK_BEFORE_STATUS> BD_BACK_BEFORE_STATUS { get; set; }
        public DbSet<BD_BACK_REASON> BD_BACK_REASON { get; set; }
        public DbSet<BD_BASE_DATA> BD_BASE_DATA { get; set; }
        public DbSet<BD_BG_MODE> BD_BG_MODE { get; set; }
        public DbSet<BD_BG_MODEL> BD_BG_MODEL { get; set; }
        public DbSet<BD_BUSINESS_TYPE> BD_BUSINESS_TYPE { get; set; }
        public DbSet<BD_BUSINESS_TYPE_PT> BD_BUSINESS_TYPE_PT { get; set; }
        public DbSet<BD_CAR_TYPE> BD_CAR_TYPE { get; set; }
        public DbSet<BD_CHARGE> BD_CHARGE { get; set; }
        public DbSet<BD_CHECK_DIF_REASON> BD_CHECK_DIF_REASON { get; set; }
        public DbSet<BD_CJFS> BD_CJFS { get; set; }
        public DbSet<BD_COMPANY_TYPE> BD_COMPANY_TYPE { get; set; }
        public DbSet<BD_COMPLETE_MEMO> BD_COMPLETE_MEMO { get; set; }
        public DbSet<BD_COMPLEX_CALC> BD_COMPLEX_CALC { get; set; }
        public DbSet<BD_COUNTRY> BD_COUNTRY { get; set; }
        public DbSet<BD_CREDIT_LEVEL> BD_CREDIT_LEVEL { get; set; }
        public DbSet<BD_CURRENCY> BD_CURRENCY { get; set; }
        public DbSet<BD_CURRENCY_AUD> BD_CURRENCY_AUD { get; set; }
        public DbSet<BD_CUSTOM> BD_CUSTOM { get; set; }
        public DbSet<BD_DELIVERY_CONTRACT> BD_DELIVERY_CONTRACT { get; set; }
        public DbSet<BD_DELIVERY_TYPE> BD_DELIVERY_TYPE { get; set; }
        public DbSet<BD_ELEMENT> BD_ELEMENT { get; set; }
        public DbSet<BD_ENTITY2FUNC> BD_ENTITY2FUNC { get; set; }
        public DbSet<BD_EXCHANGE> BD_EXCHANGE { get; set; }
        public DbSet<BD_OP_OPTYPE> BD_OP_OPTYPE { get; set; }
        public DbSet<BD_OP_TYPE> BD_OP_TYPE { get; set; }
        public DbSet<BD_PACK_TYPE> BD_PACK_TYPE { get; set; }
        public DbSet<BD_PARAM> BD_PARAM { get; set; }
        public DbSet<BD_PICK_CAR> BD_PICK_CAR { get; set; }
        public DbSet<BD_PICK_CAR_TYPE> BD_PICK_CAR_TYPE { get; set; }
        public DbSet<BD_PICK_PLT> BD_PICK_PLT { get; set; }
        public DbSet<BD_PICK_PLT_TYPE> BD_PICK_PLT_TYPE { get; set; }
        public DbSet<BD_PICK_STATION> BD_PICK_STATION { get; set; }
        public DbSet<BD_PORT_HG> BD_PORT_HG { get; set; }
        public DbSet<BD_PRODUCT_TYPE> BD_PRODUCT_TYPE { get; set; }
        public DbSet<BD_REPAIR_REASON> BD_REPAIR_REASON { get; set; }
        public DbSet<BD_SELLING_LEVEL> BD_SELLING_LEVEL { get; set; }
        public DbSet<BD_SKU_MATERIAL> BD_SKU_MATERIAL { get; set; }
        public DbSet<BD_SKU_SPEC> BD_SKU_SPEC { get; set; }
        public DbSet<BD_STORAGE_TYPE> BD_STORAGE_TYPE { get; set; }
        public DbSet<BD_TH_TYPE> BD_TH_TYPE { get; set; }
        public DbSet<BD_TRADE_WAYS> BD_TRADE_WAYS { get; set; }
        public DbSet<BD_UDF> BD_UDF { get; set; }
        public DbSet<BD_UNIT_TYPE> BD_UNIT_TYPE { get; set; }
        public DbSet<BD_URGENT_TYPE> BD_URGENT_TYPE { get; set; }
        public DbSet<BD_VOLUME_UNIT> BD_VOLUME_UNIT { get; set; }
        public DbSet<BD_WEIGHT_UNIT> BD_WEIGHT_UNIT { get; set; }
        public DbSet<BD_WH_ERROR_TYPE> BD_WH_ERROR_TYPE { get; set; }
        public DbSet<BD_WH_ERRORTYPE> BD_WH_ERRORTYPE { get; set; }
        public DbSet<BD_WH_OPLINK> BD_WH_OPLINK { get; set; }
        public DbSet<BD_WH_OPTYPE> BD_WH_OPTYPE { get; set; }
        public DbSet<BD_WH_TYPE> BD_WH_TYPE { get; set; }
        public DbSet<BD_WORK_INSTRUCTIONS> BD_WORK_INSTRUCTIONS { get; set; }
        public DbSet<BMS_ACCOUNT_ATT> BMS_ACCOUNT_ATT { get; set; }
        public DbSet<BMS_AP> BMS_AP { get; set; }
        public DbSet<BMS_AR> BMS_AR { get; set; }
        public DbSet<BMS_AUTO_DATA> BMS_AUTO_DATA { get; set; }
        public DbSet<BMS_AUTO_DATA_TRACE> BMS_AUTO_DATA_TRACE { get; set; }
        public DbSet<BMS_DZD_HEAD> BMS_DZD_HEAD { get; set; }
        public DbSet<BOCI_RULE> BOCI_RULE { get; set; }
        public DbSet<CHECK_INVENTORY> CHECK_INVENTORY { get; set; }
        public DbSet<CHECK_INVENTORY_DETAIL> CHECK_INVENTORY_DETAIL { get; set; }
        public DbSet<CLASS_TRANSFER> CLASS_TRANSFER { get; set; }
        public DbSet<CLASS_TRANSFER_DETAIL> CLASS_TRANSFER_DETAIL { get; set; }
        public DbSet<CODE_IMAGE> CODE_IMAGE { get; set; }
        public DbSet<CODESMITH_EXTENDED_PROPERTIES> CODESMITH_EXTENDED_PROPERTIES { get; set; }
        public DbSet<CONFIG_LOTTABLE> CONFIG_LOTTABLE { get; set; }
        public DbSet<CUSTOMER> CUSTOMER { get; set; }
        public DbSet<CUSTOMER_ACCOUNT_ATT> CUSTOMER_ACCOUNT_ATT { get; set; }
        public DbSet<CUSTOMER_ADDRESS> CUSTOMER_ADDRESS { get; set; }
        public DbSet<CUSTOMER_RELATION> CUSTOMER_RELATION { get; set; }
        public DbSet<CUSTOMER_ZONE> CUSTOMER_ZONE { get; set; }
        public DbSet<DEC_HEAD> DEC_HEAD { get; set; }
        public DbSet<DEMO_TABLE> DEMO_TABLE { get; set; }
        public DbSet<ECI_BASE> ECI_BASE { get; set; }
        public DbSet<ECI_CONFIG_YW> ECI_CONFIG_YW { get; set; }
        public DbSet<ECI_DATA_CODE> ECI_DATA_CODE { get; set; }
        public DbSet<ECI_DATA_GROUP> ECI_DATA_GROUP { get; set; }
        public DbSet<ECI_DATA_HELP> ECI_DATA_HELP { get; set; }
        public DbSet<ECI_DOWNLOAD> ECI_DOWNLOAD { get; set; }
        public DbSet<ECI_NO> ECI_NO { get; set; }
        public DbSet<ECI_NO_HELP> ECI_NO_HELP { get; set; }
        public DbSet<ECI_SYS_LOG> ECI_SYS_LOG { get; set; }
        public DbSet<ECI_TABLE> ECI_TABLE { get; set; }
        public DbSet<ECI_TABLE_ELEMENT> ECI_TABLE_ELEMENT { get; set; }
        public DbSet<ECI_TABLE_FUNCTION> ECI_TABLE_FUNCTION { get; set; }
        public DbSet<ECI_TABLE_GROUP> ECI_TABLE_GROUP { get; set; }
        public DbSet<ECI_TABLE_TABITEM> ECI_TABLE_TABITEM { get; set; }
        public DbSet<EMS_DETAIL> EMS_DETAIL { get; set; }
        public DbSet<EMS_HEAD> EMS_HEAD { get; set; }
        public DbSet<HIS_INVENTORY_SNAP> HIS_INVENTORY_SNAP { get; set; }
        public DbSet<INVENTORY> INVENTORY { get; set; }
        public DbSet<INVENTORY_OP> INVENTORY_OP { get; set; }
        public DbSet<INVENTORY_SNAP> INVENTORY_SNAP { get; set; }
        public DbSet<LOCATION_TRANSFER> LOCATION_TRANSFER { get; set; }
        public DbSet<LOCATION_TRANSFER_DETAIL> LOCATION_TRANSFER_DETAIL { get; set; }
        public DbSet<MMS_BASE_DATA> MMS_BASE_DATA { get; set; }
        public DbSet<MMS_BASE_DATA_DETAIL> MMS_BASE_DATA_DETAIL { get; set; }
        public DbSet<MMS_BD_PRODUCT> MMS_BD_PRODUCT { get; set; }
        public DbSet<MMS_BD_PRODUCT_SERVICE> MMS_BD_PRODUCT_SERVICE { get; set; }
        public DbSet<MMS_BD_RULE> MMS_BD_RULE { get; set; }
        public DbSet<MMS_BD_RULE_DETAIL> MMS_BD_RULE_DETAIL { get; set; }
        public DbSet<MMS_CALC_GRADE> MMS_CALC_GRADE { get; set; }
        public DbSet<MMS_CONDITION> MMS_CONDITION { get; set; }
        public DbSet<MMS_CONDITION_GROUP> MMS_CONDITION_GROUP { get; set; }
        public DbSet<MMS_CONDITION_GROUP_DETAIL> MMS_CONDITION_GROUP_DETAIL { get; set; }
        public DbSet<MMS_COST> MMS_COST { get; set; }
        public DbSet<MMS_CUST_QUOTE> MMS_CUST_QUOTE { get; set; }
        public DbSet<MMS_CUST_QUOTE_DETAIL> MMS_CUST_QUOTE_DETAIL { get; set; }
        public DbSet<MMS_CUST_TEMPLATE> MMS_CUST_TEMPLATE { get; set; }
        public DbSet<MMS_CUST_TEMPLATE_DTL> MMS_CUST_TEMPLATE_DTL { get; set; }
        public DbSet<MMS_SERVICE_TYPE> MMS_SERVICE_TYPE { get; set; }
        public DbSet<OP_CHANGE> OP_CHANGE { get; set; }
        public DbSet<OP_DECLARE_HEAD> OP_DECLARE_HEAD { get; set; }
        public DbSet<OP_HEAD> OP_HEAD { get; set; }
        public DbSet<OP_HEAD_CHANGE_WARN> OP_HEAD_CHANGE_WARN { get; set; }
        public DbSet<OP_HEAD_SETTLEMENT_TRACE> OP_HEAD_SETTLEMENT_TRACE { get; set; }
        public DbSet<OP_VENDOR_CONFIG> OP_VENDOR_CONFIG { get; set; }
        public DbSet<OPERATION_LOG> OPERATION_LOG { get; set; }
        public DbSet<OPS_HEAD> OPS_HEAD { get; set; }
        public DbSet<ORDER_BATCH> ORDER_BATCH { get; set; }
        public DbSet<ORDER_BATCH_BOCI> ORDER_BATCH_BOCI { get; set; }
        public DbSet<ORDER_BATCH_DETAIL> ORDER_BATCH_DETAIL { get; set; }
        public DbSet<ORDER_DELIVERY> ORDER_DELIVERY { get; set; }
        public DbSet<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public DbSet<ORDER_OUT> ORDER_OUT { get; set; }
        public DbSet<ORDERS> ORDERS { get; set; }
        public DbSet<PARAM_HSCODE> PARAM_HSCODE { get; set; }
        public DbSet<PARAM_UNIT> PARAM_UNIT { get; set; }
        public DbSet<PICKING> PICKING { get; set; }
        public DbSet<PICKING_DETAIL> PICKING_DETAIL { get; set; }
        public DbSet<PL_ELEMENT> PL_ELEMENT { get; set; }
        public DbSet<PL_NUM> PL_NUM { get; set; }
        public DbSet<PL_PAGE> PL_PAGE { get; set; }
        public DbSet<PL_PAGE_ASSIGN> PL_PAGE_ASSIGN { get; set; }
        public DbSet<PRODUCT> PRODUCT { get; set; }
        public DbSet<PRODUCT_BOM> PRODUCT_BOM { get; set; }
        public DbSet<PRODUCT_CONTRAST> PRODUCT_CONTRAST { get; set; }
        public DbSet<PRODUCT_PACK> PRODUCT_PACK { get; set; }
        public DbSet<PRODUCT_SKU> PRODUCT_SKU { get; set; }
        public DbSet<PRODUCT_TYPE> PRODUCT_TYPE { get; set; }
        public DbSet<PRODUCT_ZONE> PRODUCT_ZONE { get; set; }
        public DbSet<PUTAWAY> PUTAWAY { get; set; }
        public DbSet<PUTAWAY_DETAIL> PUTAWAY_DETAIL { get; set; }
        public DbSet<RECEIVE> RECEIVE { get; set; }
        public DbSet<RECEIVE_BATCH> RECEIVE_BATCH { get; set; }
        public DbSet<RECEIVE_BATCH_DETAIL> RECEIVE_BATCH_DETAIL { get; set; }
        public DbSet<RECEIVE_BSK_YQ_LOG> RECEIVE_BSK_YQ_LOG { get; set; }
        public DbSet<RECEIVE_DETAIL> RECEIVE_DETAIL { get; set; }
        public DbSet<REPAIR_ORDER> REPAIR_ORDER { get; set; }
        public DbSet<REPAIR_ORDER_MATERIAL> REPAIR_ORDER_MATERIAL { get; set; }
        public DbSet<REPAIR_ORDER_PRODUCT> REPAIR_ORDER_PRODUCT { get; set; }
        public DbSet<SSO_ENTITY2FUNC> SSO_ENTITY2FUNC { get; set; }
        public DbSet<SSO_ENTITY2ROLE> SSO_ENTITY2ROLE { get; set; }
        public DbSet<SSO_FUNCTION> SSO_FUNCTION { get; set; }
        public DbSet<SSO_NODE> SSO_NODE { get; set; }
        public DbSet<SSO_ROLE> SSO_ROLE { get; set; }
        public DbSet<SSO_USER> SSO_USER { get; set; }
        public DbSet<WAREHOUSE> WAREHOUSE { get; set; }
        public DbSet<WH_AREA> WH_AREA { get; set; }
        public DbSet<WH_LOC> WH_LOC { get; set; }
        public DbSet<WH_LOC_PRE_USE> WH_LOC_PRE_USE { get; set; }
        public DbSet<WH_ZONE> WH_ZONE { get; set; }
        public DbSet<WORK_ORDER> WORK_ORDER { get; set; }
        public DbSet<WORK_ORDER_DETAIL> WORK_ORDER_DETAIL { get; set; }
        public DbSet<BD_AREA_TYPE> BD_AREA_TYPE { get; set; }
        public DbSet<BD_COMPONENT_TYPE> BD_COMPONENT_TYPE { get; set; }
        public DbSet<BD_COMPONENT_UNIT> BD_COMPONENT_UNIT { get; set; }
        public DbSet<BD_CUSTOMER_SYS> BD_CUSTOMER_SYS { get; set; }
        public DbSet<BD_LOTS_ATTR> BD_LOTS_ATTR { get; set; }
        public DbSet<BD_LOTTABLE> BD_LOTTABLE { get; set; }
        public DbSet<BD_PRINTER> BD_PRINTER { get; set; }
        public DbSet<BD_PRODUCT_COMPONENT> BD_PRODUCT_COMPONENT { get; set; }
        public DbSet<BD_SKU_COMPONENT> BD_SKU_COMPONENT { get; set; }
        public DbSet<BD_STATUS> BD_STATUS { get; set; }
        public DbSet<BD_TRANS_MODE> BD_TRANS_MODE { get; set; }
        public DbSet<BSK_LOG> BSK_LOG { get; set; }
        public DbSet<CONFIG_EXPRESS> CONFIG_EXPRESS { get; set; }
        public DbSet<CONFIG_EXPRESS_RULE> CONFIG_EXPRESS_RULE { get; set; }
        public DbSet<CONFIG_HISDATA_CYCLE> CONFIG_HISDATA_CYCLE { get; set; }
        public DbSet<CONFIG_UI_BTN> CONFIG_UI_BTN { get; set; }
        public DbSet<CONFIG_UI_BTN_COMPANY> CONFIG_UI_BTN_COMPANY { get; set; }
        public DbSet<CRM_ENTERPRISE> CRM_ENTERPRISE { get; set; }
        public DbSet<CRM_ENTERPRISE_SERVICE> CRM_ENTERPRISE_SERVICE { get; set; }
        public DbSet<CUSTOMER_DELIVERY> CUSTOMER_DELIVERY { get; set; }
        public DbSet<CUSTOMER_TEMPLATE> CUSTOMER_TEMPLATE { get; set; }
        public DbSet<CUSTOMER_USER> CUSTOMER_USER { get; set; }
        public DbSet<I_DEC_HEAD> I_DEC_HEAD { get; set; }
        public DbSet<I_ORDER_DETAIL> I_ORDER_DETAIL { get; set; }
        public DbSet<I_ORDERS> I_ORDERS { get; set; }
        public DbSet<I_PRODUCT> I_PRODUCT { get; set; }
        public DbSet<INVENTORY_LOG> INVENTORY_LOG { get; set; }
        public DbSet<INVENTORY_QUERY> INVENTORY_QUERY { get; set; }
        public DbSet<INVENTORY_SNAP_LOG> INVENTORY_SNAP_LOG { get; set; }
        public DbSet<LOGING> LOGING { get; set; }
        public DbSet<NUCLEAR_UPDATE> NUCLEAR_UPDATE { get; set; }
        public DbSet<OP_RECEIVE_TRANSFER> OP_RECEIVE_TRANSFER { get; set; }
        public DbSet<OP_TRANSFER> OP_TRANSFER { get; set; }
        public DbSet<ORDER_BATCH_BOCI_CONFIG> ORDER_BATCH_BOCI_CONFIG { get; set; }
        public DbSet<ORDER_BATCH_BOCI_EXE> ORDER_BATCH_BOCI_EXE { get; set; }
        public DbSet<ORDER_BATCH_DETAIL_PACK> ORDER_BATCH_DETAIL_PACK { get; set; }
        public DbSet<ORDER_DELIVERY_DETAIL> ORDER_DELIVERY_DETAIL { get; set; }
        public DbSet<ORDER_DELIVERY_FILE> ORDER_DELIVERY_FILE { get; set; }
        public DbSet<ORDER_ERROR> ORDER_ERROR { get; set; }
        public DbSet<ORDER_EXPRESS_STATUS> ORDER_EXPRESS_STATUS { get; set; }
        public DbSet<ORDER_KPI> ORDER_KPI { get; set; }
        public DbSet<ORDER_OP_LOG> ORDER_OP_LOG { get; set; }
        public DbSet<ORDER_VEHICLE> ORDER_VEHICLE { get; set; }
        public DbSet<PICKING_SOURCE_INFO> PICKING_SOURCE_INFO { get; set; }
        public DbSet<PRINT_INV_TEMP> PRINT_INV_TEMP { get; set; }
        public DbSet<PRODUCT_COMPONENT> PRODUCT_COMPONENT { get; set; }
        public DbSet<PRODUCT_LOTTABLE_CUT> PRODUCT_LOTTABLE_CUT { get; set; }
        public DbSet<RECEIVE_DETAIL_COMPONENT> RECEIVE_DETAIL_COMPONENT { get; set; }
        public DbSet<RECEIVE_ERROR> RECEIVE_ERROR { get; set; }
        public DbSet<RECEIVE_FAST_MIDDLE> RECEIVE_FAST_MIDDLE { get; set; }
        public DbSet<RECEIVE_KPI> RECEIVE_KPI { get; set; }
        public DbSet<RECEIVE_VEHICLE> RECEIVE_VEHICLE { get; set; }
        public DbSet<SOURCE_PICKING_INFO> SOURCE_PICKING_INFO { get; set; }
        public DbSet<WH_WHARF> WH_WHARF { get; set; }
        public DbSet<WORK_ORDER_KPI> WORK_ORDER_KPI { get; set; }
        public DbSet<LOCATION_TRANSFER_DETAIL_VIEW> LOCATION_TRANSFER_DETAIL_VIEW { get; set; }
        public DbSet<V_CSS_ORDER_QUERY> V_CSS_ORDER_QUERY { get; set; }
        public DbSet<V_CUSTOMER> V_CUSTOMER { get; set; }
        public DbSet<V_CUSTOMER_GJDS> V_CUSTOMER_GJDS { get; set; }
        public DbSet<V_INSTR_BOOK> V_INSTR_BOOK { get; set; }
        public DbSet<V_INVENTORY_CSS_QUERY> V_INVENTORY_CSS_QUERY { get; set; }
        public DbSet<V_INVENTORY_GJDS> V_INVENTORY_GJDS { get; set; }
        public DbSet<V_INVENTORY_SNAP> V_INVENTORY_SNAP { get; set; }
        public DbSet<V_INVENTORY_SNAP_WT> V_INVENTORY_SNAP_WT { get; set; }
        public DbSet<V_LOCATION_TRANSFER_DTL_GMJK> V_LOCATION_TRANSFER_DTL_GMJK { get; set; }
        public DbSet<V_LOCATION_TRANSFER_GMJK> V_LOCATION_TRANSFER_GMJK { get; set; }
        public DbSet<V_ORDER_PACK_MT> V_ORDER_PACK_MT { get; set; }
        public DbSet<V_ORDERS_MT> V_ORDERS_MT { get; set; }
        public DbSet<V_ORDERS_RESPONSE> V_ORDERS_RESPONSE { get; set; }
        public DbSet<V_ORDERS_RESPONSE_EXPRESS> V_ORDERS_RESPONSE_EXPRESS { get; set; }
        public DbSet<V_RECEIVE_ORDER_DTL_TGPT> V_RECEIVE_ORDER_DTL_TGPT { get; set; }
        public DbSet<V_RECEIVE_ORDER_TGPT> V_RECEIVE_ORDER_TGPT { get; set; }
        public DbSet<V_SSO_USER_ROLE> V_SSO_USER_ROLE { get; set; }
        public DbSet<V_WH_LOC_GMJK> V_WH_LOC_GMJK { get; set; }
    
        public virtual int P_UP_DATE_BASE(string vAR_TABLE_NAME)
        {
            var vAR_TABLE_NAMEParameter = vAR_TABLE_NAME != null ?
                new ObjectParameter("VAR_TABLE_NAME", vAR_TABLE_NAME) :
                new ObjectParameter("VAR_TABLE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_UP_DATE_BASE", vAR_TABLE_NAMEParameter);
        }
    
        public virtual int SP_DIGIT2SPEECH(Nullable<decimal> dIGIT, ObjectParameter sPEECH)
        {
            var dIGITParameter = dIGIT.HasValue ?
                new ObjectParameter("DIGIT", dIGIT) :
                new ObjectParameter("DIGIT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DIGIT2SPEECH", dIGITParameter, sPEECH);
        }
    }
}
