//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_DECLARE_HEAD
    {
        public string GUID { get; set; }
        public string OP_DECLARE_NO { get; set; }
        public string BIZ_TYPE { get; set; }
        public string BIZ_MODE { get; set; }
        public string ENTRY_ID { get; set; }
        public string I_E_FLAG { get; set; }
        public string MANUAL_NO { get; set; }
        public string I_E_PORT { get; set; }
        public Nullable<System.DateTime> I_E_DATE { get; set; }
        public Nullable<System.DateTime> D_DATE { get; set; }
        public string DESTINATION_PORT { get; set; }
        public string TRAF_NAME { get; set; }
        public string VOYAGE_NO { get; set; }
        public string TRAF_MODE { get; set; }
        public string TRADE_CO { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string OWNER_CODE { get; set; }
        public string CONTR_NO { get; set; }
        public Nullable<decimal> IN_RATIO { get; set; }
        public string BILL_NO { get; set; }
        public string TRADE_COUNTRY { get; set; }
        public string TRADE_MODE { get; set; }
        public string CUT_MODE { get; set; }
        public string TRANS_MODE { get; set; }
        public string PAY_WAY { get; set; }
        public string FEE_MARK { get; set; }
        public string FEE_CURR { get; set; }
        public Nullable<decimal> FEE_RATE { get; set; }
        public string INSUR_MARK { get; set; }
        public string INSUR_CURR { get; set; }
        public Nullable<decimal> INSUR_RATE { get; set; }
        public string OTHER_MARK { get; set; }
        public string OTHER_CURR { get; set; }
        public Nullable<decimal> OTHER_RATE { get; set; }
        public Nullable<long> PACK_NO { get; set; }
        public Nullable<decimal> GROSS_WT { get; set; }
        public Nullable<decimal> NET_WT { get; set; }
        public string WRAP_TYPE { get; set; }
        public string LICENSE_NO { get; set; }
        public string APPR_NO { get; set; }
        public string DECL_PORT { get; set; }
        public string CO_OWNER { get; set; }
        public string EDI_ID { get; set; }
        public string M_P { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public string PRE_ENTRY_ID { get; set; }
        public string HF_NO { get; set; }
        public string SHIPPER_CODE { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string BILLING_OBJ { get; set; }
        public string CUSTOMS_COMPANY { get; set; }
        public Nullable<decimal> CC_DEC_PIAO { get; set; }
        public Nullable<decimal> CC_DEC_ZHANG { get; set; }
        public Nullable<decimal> QY_DEC_PIAO { get; set; }
        public Nullable<decimal> QY_DEC_ZHANG { get; set; }
        public Nullable<decimal> RETURN_QTY { get; set; }
        public Nullable<decimal> DELETE_QTY { get; set; }
        public Nullable<System.DateTime> QY_RETURN_DATA { get; set; }
        public Nullable<System.DateTime> QY_RETURN_CUSTOMER_DATA { get; set; }
        public Nullable<System.DateTime> CUSTOMS_LEAVE_DATE { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string INVALID_USER { get; set; }
        public Nullable<System.DateTime> INVALID_DATE { get; set; }
        public string INVALID_MEMO { get; set; }
        public string CLOCASE_USER { get; set; }
        public Nullable<System.DateTime> CLOCASE_DATE { get; set; }
    }
}
