//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_HEAD
    {
        public string OP_NO { get; set; }
        public string OP_TYPE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRICE_CODE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string HAS_CHANGE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public Nullable<System.DateTime> OP_DATE { get; set; }
        public Nullable<System.DateTime> IN_OUT_DATE { get; set; }
        public string INV_NO { get; set; }
        public string DEC_NO { get; set; }
        public Nullable<decimal> CHARGE_GW { get; set; }
        public Nullable<decimal> CHARGE_NW { get; set; }
        public Nullable<decimal> CHARGE_VOLUME { get; set; }
        public string OWNER_CODE { get; set; }
        public string WH_CODE { get; set; }
        public string MEMO { get; set; }
        public string AR_NEED_ACCOUNT { get; set; }
        public string AP_NEED_ACCOUNT { get; set; }
        public Nullable<decimal> CHARGE_VALUE { get; set; }
        public Nullable<decimal> CHARGE_TON { get; set; }
        public Nullable<decimal> CHARGE_PLT { get; set; }
        public Nullable<decimal> CHARGE_BOX { get; set; }
        public string SHIPPER_CODE { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> PIECES { get; set; }
        public Nullable<decimal> AR_OP { get; set; }
        public Nullable<decimal> AR_DD { get; set; }
        public Nullable<decimal> AP_OP { get; set; }
        public Nullable<decimal> AP_DD { get; set; }
        public string PIECES_UNIT { get; set; }
        public string STATUS { get; set; }
        public string BG_MODE { get; set; }
        public string OP_BG_MODEL { get; set; }
        public string IS_BJ { get; set; }
        public string IS_FJ { get; set; }
        public string CUSTOMER_JOB_NO { get; set; }
        public string OP_DECLARE_NO { get; set; }
        public string CONTRACT_NO { get; set; }
        public string IS_GZ { get; set; }
        public string CANCEL_GZ_USER { get; set; }
        public Nullable<System.DateTime> CANCEL_GZ_DATE { get; set; }
        public string GZ_USER { get; set; }
        public Nullable<System.DateTime> GZ_DATE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
