//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_HEAD_CHANGE_WARN
    {
        public string OP_NO { get; set; }
        public System.DateTime CHANGE_DATE { get; set; }
        public string CHANGE_USER_NAME { get; set; }
        public string DEAL_USER_NAME { get; set; }
        public Nullable<System.DateTime> DEAL_DATE { get; set; }
        public string GUID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
