//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_RECEIVE_TRANSFER
    {
        public string GUID { get; set; }
        public string MESSAGE_ID { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public string VERSION { get; set; }
        public string SENDER { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string ORDER_TYPE { get; set; }
        public string ORDER_NO { get; set; }
        public string CUSTOMER_ROLE { get; set; }
        public string CUSTOMER_B2B { get; set; }
        public string CUSTOMER_JOB_NO { get; set; }
        public string CUSTOMER_SYS { get; set; }
        public string OP_FLAG { get; set; }
        public Nullable<System.DateTime> EXE_DATE { get; set; }
        public string EXE_MEMO { get; set; }
        public string EXE_STATUS { get; set; }
        public string EXE_FLAG { get; set; }
        public string TJ_TYPE { get; set; }
        public string EXE_EXCEPTION { get; set; }
        public string EXE_USER { get; set; }
        public Nullable<System.DateTime> EXE_OP_DATE { get; set; }
        public string FILE_URL { get; set; }
    }
}
