//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_VENDOR_CONFIG
    {
        public string GUID { get; set; }
        public string SERVICE_CODE { get; set; }
        public string OP_TYPE { get; set; }
        public string CONFIG { get; set; }
        public string STATUS { get; set; }
    }
}
