//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATION_LOG
    {
        public string OP_NO { get; set; }
        public string OP_TYPE { get; set; }
        public string OP_ACTION { get; set; }
        public string OP_MEMO { get; set; }
        public string OP_USER { get; set; }
        public System.DateTime OP_DATE { get; set; }
        public string GUID { get; set; }
        public string OP_TYPE_NAME { get; set; }
    }
}
