//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPS_HEAD
    {
        public string OP_NO { get; set; }
        public Nullable<System.DateTime> ACCEPT_DATE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string SHIPPER_CODE { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string PRICE_CODE { get; set; }
        public string START_PLACE { get; set; }
        public string END_PLACE { get; set; }
        public Nullable<System.DateTime> PICK_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string SHIP_NAME { get; set; }
        public string FLIGHT_NO { get; set; }
        public string MBL { get; set; }
        public string HBL { get; set; }
        public string BILL_NO { get; set; }
        public string INV_NO { get; set; }
        public Nullable<decimal> PIECE { get; set; }
        public string PIECE_UNIT { get; set; }
        public Nullable<decimal> GW { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public string BG_AGENT { get; set; }
        public string BG_DEC_NO { get; set; }
        public Nullable<System.DateTime> BG_BG_DATE { get; set; }
        public Nullable<System.DateTime> BG_FX_DATE { get; set; }
        public Nullable<decimal> BG_PIAO { get; set; }
        public Nullable<decimal> BG_ZHANG { get; set; }
        public Nullable<decimal> BG_TD_QTY { get; set; }
        public Nullable<decimal> BG_SD_QTY { get; set; }
        public Nullable<decimal> BG_GD_QTY { get; set; }
        public string TRUCK_AGENT { get; set; }
        public string TRUCK_TYPE { get; set; }
        public string TRUCK_NO { get; set; }
        public string MEMO { get; set; }
        public string STATUS { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CANCEL_MEMO { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string CANCEL_USER { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
