//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DELIVERY
    {
        public string GUID { get; set; }
        public string WH_CODE { get; set; }
        public string STATUS { get; set; }
        public string DELIVERY_NO { get; set; }
        public string DELIVERY_COMPANY { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string CAR_NO { get; set; }
        public string PERSON { get; set; }
        public string TEL { get; set; }
        public string DELIVERY_ADDRESS { get; set; }
        public string DELIVERY_EREA { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> LOADING_FINISH_DATE { get; set; }
        public string WH_TYPE { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public string RECEIVE_USER { get; set; }
        public string CAR_TYPE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string STORE_USER { get; set; }
        public string EXTERNAL_KEY { get; set; }
        public string BOX_NO { get; set; }
        public string DELIVERY_DRIVER { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
