//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_KPI
    {
        public string GUID { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_BATCH_NO { get; set; }
        public string WH_TYPE { get; set; }
        public string WH_CODE { get; set; }
        public string OP_LINK { get; set; }
        public string OP_TYPE { get; set; }
        public string OP_USER { get; set; }
        public string OP_NUM { get; set; }
        public Nullable<System.DateTime> OP_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string VENDOR_CODE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
