//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_BATCH_BOCI_EXE
    {
        public string GUID { get; set; }
        public string EXE_NO { get; set; }
        public string FILTER_GUID { get; set; }
        public string IS_SUCCESS { get; set; }
        public string IS_AUTO { get; set; }
        public Nullable<System.DateTime> EXE_DATE { get; set; }
        public string EXE_USER { get; set; }
        public string WH_CODE { get; set; }
        public string FLT_CUSTOMER_CODE { get; set; }
        public string FLT_BUSINESS_TYPE { get; set; }
        public string FLT_CUSTOMER_SYS { get; set; }
        public string FLT_DELIVERY_COMPANY { get; set; }
        public Nullable<decimal> FLT_SHIP_DATE_START { get; set; }
        public Nullable<decimal> FLT_SHIP_DATE_END { get; set; }
        public Nullable<decimal> FLT_ORDER_LINE_START { get; set; }
        public Nullable<decimal> FLT_ORDER_LINE_END { get; set; }
        public Nullable<decimal> FLT_ORDER_PL_START { get; set; }
        public Nullable<decimal> FLT_ORDER_PL_END { get; set; }
        public Nullable<decimal> FLT_QTY_START { get; set; }
        public Nullable<decimal> FLT_QTY_END { get; set; }
        public Nullable<decimal> FLT_WEIGHT_START { get; set; }
        public Nullable<decimal> FLT_WEIGHT_END { get; set; }
        public Nullable<decimal> FLT_VOLUME_START { get; set; }
        public Nullable<decimal> FLT_VOLUME_END { get; set; }
        public string SPT_CUSTOMER_CODE { get; set; }
        public string SPT_CUSTOMER_SYS { get; set; }
        public Nullable<decimal> SPT_ORDER_NUM_START { get; set; }
        public Nullable<decimal> SPT_ORDER_NUM_END { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public string SPT_DELIVERY_COMPANY { get; set; }
        public string EXE_MEMO { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
