//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_BATCH
    {
        public string GUID { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_BATCH_NO { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string WH_CODE { get; set; }
        public string STATUS { get; set; }
        public string ASSIGN_METHOD { get; set; }
        public string PACK_METHOD { get; set; }
        public Nullable<System.DateTime> ASSIGN_DATE { get; set; }
        public string PICK_EXPLAIN { get; set; }
        public Nullable<System.DateTime> PICK_DATE { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public string SHIP_EXPLAIN { get; set; }
        public string SHIP_CAR { get; set; }
        public string LOAD_USER { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string POD_USER { get; set; }
        public Nullable<System.DateTime> POD_DATE { get; set; }
        public string DELIVERY_PLAN { get; set; }
        public string CHECK_USER { get; set; }
        public string SHIP_REMARK { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string TS_VERSION { get; set; }
        public string BOCI_NO { get; set; }
        public string BILLING_OBJ { get; set; }
        public string EMS_NO { get; set; }
        public Nullable<decimal> TOTAL_GW { get; set; }
        public Nullable<decimal> TOTAL_NW { get; set; }
        public Nullable<decimal> TOTAL_VOLUME { get; set; }
        public string ORDER_INVOICE { get; set; }
        public Nullable<decimal> TOTAL_CTN { get; set; }
        public Nullable<decimal> TOTAL_PLT { get; set; }
        public Nullable<decimal> TOTAL_PIECE { get; set; }
        public string PIECES_UNIT { get; set; }
        public string INVALID_USER { get; set; }
        public Nullable<System.DateTime> INVALID_DATE { get; set; }
        public string INVALID_MEMO { get; set; }
        public string WH_TYPE { get; set; }
        public string RT_STATUS { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> CONFIRM_DATE { get; set; }
        public Nullable<System.DateTime> RECHECK_DATE { get; set; }
        public string ABNORMAL { get; set; }
        public string PACK_STATUS { get; set; }
        public string VOYAGE { get; set; }
        public string STORE_USER { get; set; }
        public string BILL_USER { get; set; }
        public string IS_JB { get; set; }
        public string SHIP_WG_NO { get; set; }
        public string IS_XCCJ { get; set; }
        public string BOCI_GUID { get; set; }
        public string PICK_PLT_NO { get; set; }
        public string WH_WHARF { get; set; }
        public string DELIVERY_DRIVER { get; set; }
        public string BOX_NO { get; set; }
        public Nullable<decimal> ACTUAL_WEIGH { get; set; }
        public string DELIVERY_COMPANY { get; set; }
        public string IS_ZS { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
