//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_BATCH_DETAIL_PACK
    {
        public string GUID { get; set; }
        public string ORDER_DETAIL_GUID { get; set; }
        public string ORDER_BATCH_DETAIL_GUID { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_BATCH_NO { get; set; }
        public string RECEIVE_NO { get; set; }
        public string RECEIVE_BATCH_NO { get; set; }
        public string PUTAWAY_NO { get; set; }
        public string INVENTORY_GUID { get; set; }
        public string RECEIVE_BATCH_DETAIL_GUID { get; set; }
        public string REEL_NO { get; set; }
        public string DATE_CODE { get; set; }
        public string LOT_CODE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<decimal> LINE_NO { get; set; }
        public decimal ORDER_LINE_NO { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
