//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_BATCH_BOCI
    {
        public string GUID { get; set; }
        public string BOCI_NO { get; set; }
        public string PICK_METHOD { get; set; }
        public Nullable<System.DateTime> BOCI_CREATE_DATE { get; set; }
        public string BOCI_CREATE_USER { get; set; }
        public string BOCI_EXE_GUID { get; set; }
        public string BOCI_EXE_NO { get; set; }
        public string WH_TYPE { get; set; }
        public string WH_CODE { get; set; }
        public string RT_STATUS { get; set; }
        public string LOC_PICK_SEQ { get; set; }
        public string STATUS { get; set; }
        public string PICK_STATION_NO { get; set; }
        public string MEMO { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string TS_VERSION { get; set; }
        public string BOCI_TYPE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
