//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_ELEMENT
    {
        public string ID { get; set; }
        public string PAGE_ID { get; set; }
        public string ELEMENT_TYPE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string DB_CODE { get; set; }
        public string DB_DATA_TYPE { get; set; }
        public string DICTIONARY_TYPE { get; set; }
        public string DICTIONARY_TYPE_CONFIG { get; set; }
        public Nullable<decimal> DB_LENGTH { get; set; }
        public string QUERY_ATTRIBUTE { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string DEFAULT_VALUE_EDIT { get; set; }
        public string DEFAULT_VALUE_QUERY { get; set; }
        public string GRID_SHOW { get; set; }
        public string EDIT_SHOW { get; set; }
        public string QUERY_SHOW { get; set; }
        public Nullable<decimal> GRID_SEQ { get; set; }
        public Nullable<decimal> EDIT_SEQ { get; set; }
        public Nullable<decimal> QUERY_SEQ { get; set; }
        public string PRIMARY_KEY { get; set; }
        public string NULLABLE_KEY { get; set; }
        public string UNIQUE_KEY { get; set; }
        public string DICTIONARY_TYPE_PARAM { get; set; }
        public Nullable<decimal> PRIMARY_KEY_AUTO_TYPE { get; set; }
        public Nullable<decimal> DEFAULT_SORT { get; set; }
        public string LOCK_MODE { get; set; }
        public string SYSTEM_DATA { get; set; }
        public string SYSTEM_DATA_TRIGGER { get; set; }
        public Nullable<decimal> SYSTEM_DATA_SHOW { get; set; }
        public Nullable<decimal> BATCH_UPDATE_SHOW { get; set; }
        public Nullable<decimal> SUM_FIELD { get; set; }
        public Nullable<decimal> JL_FLAG { get; set; }
        public Nullable<decimal> COLSPAN { get; set; }
        public Nullable<decimal> SYSTEM_DATA_SHOW_WHEN_ADD { get; set; }
        public string SHOW_CONVERT { get; set; }
        public string PRIMARY_CREATOR { get; set; }
        public string COPY_REMOVE_DATA { get; set; }
        public string QUERY_ADD_EMPTY { get; set; }
        public string GROUP_CODE { get; set; }
        public string START_NEW_ROW_EDIT { get; set; }
        public string START_NEW_ROW_QUERY { get; set; }
        public string NOT_SAVE { get; set; }
        public string HIDDEN { get; set; }
        public string GRID_TEMPLATE { get; set; }
        public string FROM_DATA_SOURCE { get; set; }
        public string DATA_FORMAT_GRID { get; set; }
        public string DATA_FORMAT_EDIT { get; set; }
        public string EDIT_TIP { get; set; }
        public string AFTER_ELEMENT { get; set; }
        public string GOD_CODE { get; set; }
        public string ON_CHANGED_FUNCTION { get; set; }
        public string PL_PARAM { get; set; }
        public string PL_VALIDATE { get; set; }
        public string POWER_NO { get; set; }
        public string DISPLAY_TYPE { get; set; }
        public string SHOW_NAME { get; set; }
        public Nullable<decimal> COLUMN_COUNT { get; set; }
        public string PAGE_CODE { get; set; }
        public string PAGE_TYPE { get; set; }
        public string SEND_PARENT_NOTICE { get; set; }
        public string RECEIVE_PARENT_NOTICE { get; set; }
        public string SEND_CONFIG { get; set; }
        public string RECEIVE_CONFIG { get; set; }
        public string ASSEMBLY { get; set; }
        public string CLASS_NAME { get; set; }
        public string FUNCTION_TYPE { get; set; }
        public string SHOW_MODE { get; set; }
        public string HOT_KEY { get; set; }
        public string STD_COMMAND { get; set; }
        public string STD_COMMAND_CONFIG { get; set; }
        public string NEED_CONFIRM { get; set; }
        public string SERVICE_ASSEMBLY { get; set; }
        public string SERVICE_CONFIG { get; set; }
        public string ICON { get; set; }
        public string XAP_NAME { get; set; }
        public string NEED_DOWNLOAD { get; set; }
        public string SERVICE_CLASS_NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string MEMO { get; set; }
    }
}
