//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_PAGE
    {
        public string DB_NAME { get; set; }
        public string PAGE_NAME { get; set; }
        public string ID { get; set; }
        public string DISPLAY_WIDTH { get; set; }
        public string CASCADE { get; set; }
        public Nullable<decimal> DISPLAY_COLUMN_COUNT { get; set; }
        public string CODE { get; set; }
        public string DEFAULT_CONDITION { get; set; }
        public string DEFAULT_LOAD_DATA { get; set; }
        public string FUNCTION_ADD { get; set; }
        public string FUNCTION_DELETE { get; set; }
        public string FUNCTION_EXCEL { get; set; }
        public string FUNCTION_EDIT { get; set; }
        public string DEFAULT_SORT { get; set; }
        public string GRID_SQL { get; set; }
        public string PAGE_TYPE { get; set; }
        public string GRID_DBLCLICK_FUNCTION { get; set; }
        public Nullable<decimal> DEFAULT_PAGE_SIZE { get; set; }
        public string FUNCTION_BACK { get; set; }
        public string MEMO { get; set; }
        public string PAGE_TITLE { get; set; }
        public Nullable<decimal> QUERY_COLUMN_COUNT { get; set; }
        public string FUNCTION_COPY { get; set; }
        public string SOURCE_CONTROL_LOCK { get; set; }
        public string CHOOSE_MULTI_SELECT { get; set; }
        public string DEFAULT_SELECT { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string GRID_LAYOUT { get; set; }
        public string AFTER_SAVE_TO_ADD_STATUS { get; set; }
        public string AFTER_SAVE_REFRESH_LIST { get; set; }
        public string UDF8 { get; set; }
        public string QUERY_TYPE { get; set; }
        public string ADD_TITLE { get; set; }
        public string EDIT_TITLE { get; set; }
        public string BATCH_COLUMN_COUNT { get; set; }
        public string BATCH_DISPLAY_WIDTH { get; set; }
        public string UDF13 { get; set; }
        public string UDF14 { get; set; }
        public string ER_ADD { get; set; }
        public string ER_DELETE { get; set; }
        public string ER_INIT { get; set; }
        public string UDF18 { get; set; }
        public string UDF19 { get; set; }
        public string UDF20 { get; set; }
        public string SYS_CODE { get; set; }
        public string ADD_USE_TAB { get; set; }
        public string EDIT_USE_TAB { get; set; }
        public string QUERY_PL_PAGE_CODE { get; set; }
        public string LIST_PL_PAGE_CODE { get; set; }
        public string EDIT_PL_PAGE_CODE { get; set; }
        public string EDIT_LAYOUT { get; set; }
        public string PL_SAVE_REFRESH { get; set; }
        public string PL_VERSION { get; set; }
        public string SAVE_FIXED { get; set; }
        public string NOTICE_SUB_MY_CHANGE { get; set; }
        public string NOTICE_MAIN_MY_CHANGE { get; set; }
        public string DEAL_MAIN_CHANGE { get; set; }
        public string DEAL_SUB_CHANGE { get; set; }
        public string DEAL_MAIN_CHANGE_FUNCTION { get; set; }
        public string DEAL_SUB_CHANGE_FUNCTION { get; set; }
        public string NEED_COMMAND_LIST { get; set; }
        public string NEED_COMMAND_EDIT { get; set; }
        public string DISPLAY_CHECK { get; set; }
        public string DISPLAY_SEQ { get; set; }
        public string DATA_CHOOSE { get; set; }
        public string PAGING_TYPE { get; set; }
        public string EDIT_AREA_SETTING { get; set; }
        public string QUERY_AREA_SETTING { get; set; }
        public string DISPLAY_EDIT_ICON { get; set; }
        public string PL_PARAM { get; set; }
        public string CHOOSE_INPUT { get; set; }
        public string CHOOSE_OUTPUT { get; set; }
        public string CHOOSE_CONVERT { get; set; }
        public string CHOOSE_CONFIG { get; set; }
        public string NEED_TRACE_UPWARD { get; set; }
        public string IS_TEMP_SAVE { get; set; }
        public string NEED_DOWNLOAD { get; set; }
        public string EDIT_FUNCTION_ADD { get; set; }
        public string EDIT_FUNCTION_SAVE { get; set; }
        public string EDIT_FUNCTION_COPY { get; set; }
        public string EDIT_FUNCTION_CLOSE { get; set; }
        public string ROW_DETAIL { get; set; }
        public string WCF_CHECK_CONFIG { get; set; }
        public string CHOOSE_CODE { get; set; }
        public string CHOOSE_NAME { get; set; }
        public string HELP_CODE { get; set; }
        public string AFTER_LOAD_CONTROL_CONFIG { get; set; }
        public Nullable<decimal> DISPLAY_HEIGHT { get; set; }
        public string POP_EDIT { get; set; }
        public string PRIMARY_KEY_INPUT { get; set; }
        public string DATA_SOURCE { get; set; }
        public string DATA_SOURCE_MEMO { get; set; }
    }
}
