//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_PAGE_ASSIGN
    {
        public string GUID { get; set; }
        public string IP { get; set; }
        public string URL { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
