//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public string GUID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string SKU { get; set; }
        public string SKU_DESC { get; set; }
        public string SKU_CUSTOM_DESC { get; set; }
        public string HSCODE { get; set; }
        public string HSITEM { get; set; }
        public string STORAGE_TYPE { get; set; }
        public Nullable<decimal> STOCK_PRICE { get; set; }
        public Nullable<decimal> SALES_PRICE { get; set; }
        public Nullable<decimal> SAFETY_STOCK { get; set; }
        public string BILL_PACK { get; set; }
        public string OTHER_NAME { get; set; }
        public string STATUS { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string PICK_TYPE { get; set; }
        public string PUTAWAY_TYPE { get; set; }
        public string BAR_CODE { get; set; }
        public string ASSIGN_METHOD { get; set; }
        public string PACK_METHOD { get; set; }
        public string UNIT { get; set; }
        public string WH_BAHNO { get; set; }
        public string PUTCHECK_FLAG { get; set; }
        public string PRODUCT_BRAND { get; set; }
        public string PRODUCT_STATUS { get; set; }
        public Nullable<decimal> PRODUCT_LENGTH { get; set; }
        public Nullable<decimal> PRODUCT_WIDTH { get; set; }
        public Nullable<decimal> PRODUCT_HEIGHT { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
