//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUTAWAY
    {
        public string GUID { get; set; }
        public string RECEIVE_NO { get; set; }
        public string RECEIVE_BATCH_NO { get; set; }
        public string PUTAWAY_NO { get; set; }
        public string WH_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> PUTAWAY_DATE { get; set; }
        public string PUTAWAY_USER { get; set; }
        public string PUTAWAY_EXPLAIN { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string PUTAWAY_RULE { get; set; }
        public string IS_NOT_USE { get; set; }
        public string IS_SAME_ZONE { get; set; }
        public string IS_ONE_LOC { get; set; }
        public string IS_DEFAULT_ZONE { get; set; }
        public string TS_VERSION { get; set; }
        public string PUTAWAY_REQUEST { get; set; }
        public string RFID { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
