//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVE_BATCH_DETAIL
    {
        public string GUID { get; set; }
        public string RECEIVE_DETAIL_GUID { get; set; }
        public string RECEIVE_NO { get; set; }
        public string RECEIVE_BATCH_NO { get; set; }
        public string WH_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string SKU { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string CONSIGNEE_SKU { get; set; }
        public string NOTIFY_CODE { get; set; }
        public string NOTIFY_SKU { get; set; }
        public string LOT_NO { get; set; }
        public string INV_NO { get; set; }
        public string PO_NO { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> DATECODE { get; set; }
        public string CUSTOMER_REF_NO { get; set; }
        public string CONSIGNEE_REF_NO { get; set; }
        public string NOTIFY_REF_NO { get; set; }
        public Nullable<decimal> PIRCE { get; set; }
        public Nullable<decimal> UNIT_GW { get; set; }
        public Nullable<decimal> UNIT_NW { get; set; }
        public Nullable<decimal> UNIT_VOLUME { get; set; }
        public Nullable<decimal> EXTERNAL_QTY { get; set; }
        public Nullable<decimal> RECEIPT_QTY { get; set; }
        public Nullable<decimal> PUTAWAY_QTY { get; set; }
        public Nullable<decimal> GOOD_QTY { get; set; }
        public Nullable<decimal> NG_QTY { get; set; }
        public Nullable<decimal> UNKNOWN_QTY { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public Nullable<decimal> PACK1 { get; set; }
        public Nullable<decimal> PACK2 { get; set; }
        public Nullable<decimal> PACK3 { get; set; }
        public Nullable<decimal> PACK4 { get; set; }
        public Nullable<decimal> PACK5 { get; set; }
        public Nullable<decimal> PACK6 { get; set; }
        public string PACK1_UNIT { get; set; }
        public string PACK2_UNIT { get; set; }
        public string PACK3_UNIT { get; set; }
        public string PACK4_UNIT { get; set; }
        public string PACK5_UNIT { get; set; }
        public string PACK6_UNIT { get; set; }
        public string TS_VERSION { get; set; }
        public decimal LINE_NO { get; set; }
        public Nullable<decimal> G_NO { get; set; }
        public string HSCODE { get; set; }
        public string HSNAME { get; set; }
        public string SB_UNIT { get; set; }
        public string ONE_UNIT { get; set; }
        public string TWO_UNIT { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> PACK_GW { get; set; }
        public Nullable<decimal> PACK_NW { get; set; }
        public Nullable<decimal> PACK_VOLUME { get; set; }
        public string PACK_STR { get; set; }
        public string PACK_NO_PRE { get; set; }
        public Nullable<decimal> PACK_NO_LENGTH { get; set; }
        public Nullable<decimal> PACK_NO_START { get; set; }
        public Nullable<decimal> PACK_NO_END { get; set; }
        public string PACK_MEASURE { get; set; }
        public Nullable<decimal> PACK_NUM { get; set; }
        public decimal YB_LINE_NO { get; set; }
        public string DAMAGE_FLAG { get; set; }
        public Nullable<decimal> PACK_MAX { get; set; }
        public string PACK_UNIT_MAX { get; set; }
        public string PACK_NO_STR { get; set; }
        public string TEMP { get; set; }
        public Nullable<decimal> CHECK_QTY { get; set; }
        public Nullable<decimal> CONTAINER_QTY { get; set; }
        public string CONTAINER_NO { get; set; }
        public Nullable<decimal> PACK_MJ { get; set; }
        public string ONLY_NO { get; set; }
        public string IS_CONTROL { get; set; }
        public string UNIQUE_CODE { get; set; }
        public Nullable<System.DateTime> CUSTOMER_SHIP_DATE { get; set; }
        public string SPEC { get; set; }
        public string MATERIAL { get; set; }
        public string PACKAGE_NO { get; set; }
        public string OWN_NO { get; set; }
        public Nullable<System.DateTime> PUTAWAY_DATE { get; set; }
        public string SHIPPER_CODE { get; set; }
        public string EMS_NO { get; set; }
        public string PACK_NO { get; set; }
        public Nullable<decimal> PIECES { get; set; }
        public Nullable<decimal> TOTAL_GW { get; set; }
        public string MEMO { get; set; }
        public string PLT_UNIT { get; set; }
        public Nullable<decimal> SJ_GW { get; set; }
        public Nullable<decimal> SJ_NW { get; set; }
        public Nullable<decimal> SJ_VOLUME { get; set; }
        public string UDF11 { get; set; }
        public string UDF12 { get; set; }
        public string UDF13 { get; set; }
        public string UDF14 { get; set; }
        public string UDF15 { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
