//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVE_DETAIL_COMPONENT
    {
        public string GUID { get; set; }
        public string RECEIVE_NO { get; set; }
        public string RECEIVE_DETAIL_GUID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string SKU { get; set; }
        public string COMPONENT { get; set; }
        public string COMPONENT_TYPE { get; set; }
        public string COMPONENT_UNIT { get; set; }
        public string GK_RANGE { get; set; }
        public Nullable<decimal> EXTERNAL_SCALE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> GK_BEGIN_DATA { get; set; }
        public Nullable<decimal> GK_END_DATA { get; set; }
        public string GK_BEGIN_FLAG { get; set; }
        public string GK_END_FLAG { get; set; }
        public Nullable<decimal> SCALE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    }
}
