//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CSS_ORDER_QUERY
    {
        public string CUSTOMER_CODE { get; set; }
        public Nullable<System.DateTime> PICK_DATE { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public string ORDER_NO { get; set; }
        public string STATUS { get; set; }
        public string SKU { get; set; }
        public string NOTIFY_CODE { get; set; }
        public string NOTIFY_SKU { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string CONSIGNEE_SKU { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public Nullable<decimal> PICK_QTY { get; set; }
        public Nullable<decimal> SHIP_QTY { get; set; }
        public Nullable<decimal> GOOD_QTY { get; set; }
        public Nullable<decimal> NG_QTY { get; set; }
        public Nullable<decimal> UNKNOWN_QTY { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string PO_NO { get; set; }
        public string ORDER_INVOICE { get; set; }
        public string INV_NO { get; set; }
        public string WH_CODE { get; set; }
        public string CUSTOMS_JOB_NO { get; set; }
        public string ORG_CODE { get; set; }
        public string PACK_NO { get; set; }
    }
}
