//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CUSTOMER
    {
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_SNAME { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_ENAME { get; set; }
        public string EADDRESS { get; set; }
        public string ADDRESS { get; set; }
        public string LINKER { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string CIQID { get; set; }
        public string REMARK { get; set; }
        public string EDITWHO { get; set; }
        public string STATUS { get; set; }
    }
}
