//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CUSTOMER_GJDS
    {
        public string LABLENAME { get; set; }
        public Nullable<System.Guid> MESSAGE_ID { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public string VERSION { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string CUSTOM_NO { get; set; }
        public string CUSTOMER_B2B { get; set; }
        public string WH_CUSTOM_NO { get; set; }
    }
}
