//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVENTORY_SNAP
    {
        public string STORERKEY { get; set; }
        public string COP_G_NO { get; set; }
        public string RDATE { get; set; }
        public string TRADE_CO { get; set; }
        public string WH_LOC { get; set; }
        public Nullable<decimal> G_QTY { get; set; }
        public Nullable<decimal> QTY_1 { get; set; }
        public Nullable<decimal> QTY_2 { get; set; }
        public string TRADE_CURR { get; set; }
        public Nullable<decimal> TRADE_TOTAL { get; set; }
        public string SYSCODE { get; set; }
        public string STATUS { get; set; }
        public string G_F_TIME { get; set; }
        public string GOODS_TYPE { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public string READ_FLAG { get; set; }
    }
}
