//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVENTORY_GJDS
    {
        public string GUID { get; set; }
        public string CUSTOM_AREA { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public string EMS_NO { get; set; }
        public string BIZ_TYPE { get; set; }
        public string H_EMS_NO { get; set; }
        public string TRADE_CODE { get; set; }
        public string TRADE_NAME { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> STOCK_AMOUT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string IS_DEAL { get; set; }
        public string EXTEND_FIELD_3 { get; set; }
        public string EXTEND_FIELD_4 { get; set; }
        public string READ_FLAG { get; set; }
    }
}
