//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVENTORY_CSS_QUERY
    {
        public string WH_CODE { get; set; }
        public System.DateTime PUTAWAY_DATE { get; set; }
        public string SHIPPER_CODE { get; set; }
        public string SHIPPER_NAME { get; set; }
        public string WH_NAME { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string SKU { get; set; }
        public string SKU_DESC { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string CONSIGNEE_NAME { get; set; }
        public string CONSIGNEE_SKU { get; set; }
        public string NOTIFY_CODE { get; set; }
        public string NOTIFY_NAME { get; set; }
        public string NOTIFY_SKU { get; set; }
        public Nullable<decimal> GOOD_QTY { get; set; }
        public Nullable<decimal> NG_QTY { get; set; }
        public Nullable<decimal> UNKNOWN_QTY { get; set; }
        public string CUSTOMERS_JOB_NO { get; set; }
        public string RECEIVE_NO { get; set; }
        public string LOT_NO { get; set; }
        public string INV_NO { get; set; }
        public string PO_NO { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> DATECODE { get; set; }
        public string CUSTOMER_REF_NO { get; set; }
        public string CONSIGNEE_REF_NO { get; set; }
        public string NOTIFY_REF_NO { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public string PACK_NO { get; set; }
        public string PACK_STR { get; set; }
        public decimal YB_LINE_NO { get; set; }
        public string UNIQUE_CODE { get; set; }
        public Nullable<System.DateTime> CUSTOMER_SHIP_DATE { get; set; }
        public string MATERIAL { get; set; }
        public string PACKAGE_NO { get; set; }
        public string OWN_NO { get; set; }
        public string IS_CONTROL { get; set; }
        public string UDF11 { get; set; }
        public string UDF12 { get; set; }
        public string UDF13 { get; set; }
        public string UDF14 { get; set; }
        public string UDF15 { get; set; }
        public string CURRENCY_CODE { get; set; }
        public decimal QTY { get; set; }
        public Nullable<decimal> PIRCE { get; set; }
        public string ORG_CODE { get; set; }
    }
}
