//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVENTORY_SNAP_WT
    {
        public string WT { get; set; }
        public string VENDORCODE { get; set; }
        public string CONSIGNEE_CODE { get; set; }
        public string SKU { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public string FILENAME { get; set; }
    }
}
