//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INSTR_BOOK
    {
        public string GUID { get; set; }
        public string ORDER_BATCH_NO { get; set; }
        public string SKU { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string INSTRNO { get; set; }
        public string DESTAREA { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public Nullable<decimal> ASSIGN_QTY { get; set; }
        public string ORDER_PLT_NO { get; set; }
        public string MACHINE_TYPE { get; set; }
        public string WH_CODE { get; set; }
        public string ZONE_NAME { get; set; }
        public string AREA_NAME { get; set; }
    }
}
