//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LOCATION_TRANSFER_DTL_GMJK
    {
        public string SEQ_NO { get; set; }
        public string OUT_STORE_BILL_NO { get; set; }
        public string OUT_TIN_GUID { get; set; }
        public string OUT_TIN_ID { get; set; }
        public string OUT_TIN_NAME { get; set; }
        public string COP_G_NO { get; set; }
        public Nullable<decimal> G_NO { get; set; }
        public string CODE_T_S { get; set; }
        public string G_NAME { get; set; }
        public Nullable<decimal> IN_QTY { get; set; }
        public string IN_UNIT { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string IN_TIN_ID { get; set; }
        public string IN_TIN_NAME { get; set; }
    }
}
