//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LOCATION_TRANSFER_GMJK
    {
        public string LABLENAME { get; set; }
        public string SEQ_NO { get; set; }
        public string PLAT_NO2 { get; set; }
        public string EMS_NO { get; set; }
        public string TRADE_CODE { get; set; }
        public string TRADE_NAME { get; set; }
        public Nullable<System.DateTime> CHANGE_START_DATE { get; set; }
        public Nullable<System.DateTime> CHANGE_END_DATE { get; set; }
        public string CHANGE_REMARK { get; set; }
        public string REMARK { get; set; }
        public string AREA_CODE { get; set; }
        public string CUSTOMS_CODE { get; set; }
        public string OP_COMPANYCODE { get; set; }
    }
}
