//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORDERS_RESPONSE_EXPRESS
    {
        public string ORDER_NO { get; set; }
        public string DELIVERY_NO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> OP_DATE { get; set; }
    }
}
