//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORDER_PACK_MT
    {
        public string GUID { get; set; }
        public string STOCKOUTGUID { get; set; }
        public string ORDER_NO { get; set; }
        public string REELNO { get; set; }
        public string DATECODE { get; set; }
        public string LOTNO { get; set; }
    }
}
