//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORDERS_RESPONSE
    {
        public string LABLENAME { get; set; }
        public string CUSTOM_AREA { get; set; }
        public string CUSTOM_AREA_BIZ { get; set; }
        public string ORDERNO { get; set; }
        public string SYSCODE { get; set; }
        public string WAREHSENO { get; set; }
        public string ASNSONO { get; set; }
        public string ORDER_TYPE { get; set; }
        public string CUSTOM_JOB_NO { get; set; }
        public string OP_STATUS { get; set; }
        public Nullable<System.DateTime> OP_DATE { get; set; }
        public string VERDOR { get; set; }
        public string TRADE_CODE { get; set; }
        public string TRADE_NAME { get; set; }
        public string TRANSPORT_BILL_NO { get; set; }
        public string LOGISTCS_CODE { get; set; }
        public string LOGISTCS_NAME { get; set; }
        public string EP_CODE { get; set; }
        public string EP_NAME { get; set; }
        public string CUSTOMS_CODE { get; set; }
        public string REGION_CODE { get; set; }
    }
}
