//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ORDERS_MT
    {
        public string GUID { get; set; }
        public string STOCKOUTGUID { get; set; }
        public string CALLMATERIALNO { get; set; }
        public string PARTNO { get; set; }
        public string VENDORCODE { get; set; }
        public string MRPAREA { get; set; }
        public string STOCKOUTNO { get; set; }
        public Nullable<System.DateTime> STOCKOUTTIME { get; set; }
        public Nullable<decimal> STOCKOUTQTY { get; set; }
        public Nullable<decimal> NETWEIGHT { get; set; }
        public string NETWEIGHTUNIT { get; set; }
    }
}
