//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RECEIVE_ORDER_TGPT
    {
        public string GUID { get; set; }
        public string APPTYPE { get; set; }
        public string APPTIME { get; set; }
        public string APPSTATUS { get; set; }
        public string CUSTOMSCODE { get; set; }
        public string COPNO { get; set; }
        public string OPERATORCODE { get; set; }
        public string OPERATORNAME { get; set; }
        public string IEFLAG { get; set; }
        public string TRAFMODE { get; set; }
        public string TRAFNO { get; set; }
        public string VOYAGENO { get; set; }
        public string BILLNO { get; set; }
        public string LOGISTICSCODE { get; set; }
        public string LOGISTICSNAME { get; set; }
        public string ORG_CODE { get; set; }
    }
}
