//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        public WAREHOUSE()
        {
            this.WH_ZONE = new HashSet<WH_ZONE>();
        }
    
        public string GUID { get; set; }
        public string WH_CODE { get; set; }
        public string WH_NAME { get; set; }
        public string WH_SHORT_NAME { get; set; }
        public string WH_EN_NAME { get; set; }
        public string WH_TYPE { get; set; }
        public string ADDRESS { get; set; }
        public string PERSON { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string STATUS { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CUSTOM_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string IS_RF { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    
        public virtual ICollection<WH_ZONE> WH_ZONE { get; set; }
    }
}
