//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_AREA
    {
        public WH_AREA()
        {
            this.WH_LOC = new HashSet<WH_LOC>();
        }
    
        public string GUID { get; set; }
        public string WH_CODE { get; set; }
        public string ZONE_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string AREA_NAME { get; set; }
        public string AREA_TYPE { get; set; }
        public string STORAGE_TYPE { get; set; }
        public string STATUS { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string ZONE_GUID { get; set; }
        public Nullable<decimal> PICK_SEQ { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    
        public virtual WH_ZONE WH_ZONE { get; set; }
        public virtual ICollection<WH_LOC> WH_LOC { get; set; }
    }
}
