//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_ZONE
    {
        public WH_ZONE()
        {
            this.WH_AREA = new HashSet<WH_AREA>();
        }
    
        public string GUID { get; set; }
        public string WH_CODE { get; set; }
        public string ZONE_CODE { get; set; }
        public string ZONE_NAME { get; set; }
        public string LOCATION { get; set; }
        public string AREA { get; set; }
        public string PERSON { get; set; }
        public string STATUS { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string WAREHOUSE_GUID { get; set; }
        public Nullable<decimal> PICK_SEQ { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
    
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        public virtual ICollection<WH_AREA> WH_AREA { get; set; }
    }
}
